"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from waChatLockSettings import WAWebProtobufsChatLockSettings_pb2 as _WAWebProtobufsChatLockSettings_pb2
from waCommon import WACommon_pb2 as _WACommon_pb2
from waE2E import WAWebProtobufsE2E_pb2 as _WAWebProtobufsE2E_pb2
from waSyncAction import WAWebProtobufSyncAction_pb2 as _WAWebProtobufSyncAction_pb2
from waWeb import WAWebProtobufsWeb_pb2 as _WAWebProtobufsWeb_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _MediaVisibility:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MediaVisibilityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MediaVisibility.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEFAULT: _MediaVisibility.ValueType  # 0
    OFF: _MediaVisibility.ValueType  # 1
    ON: _MediaVisibility.ValueType  # 2

class MediaVisibility(_MediaVisibility, metaclass=_MediaVisibilityEnumTypeWrapper): ...

DEFAULT: MediaVisibility.ValueType  # 0
OFF: MediaVisibility.ValueType  # 1
ON: MediaVisibility.ValueType  # 2
Global___MediaVisibility: _TypeAlias = MediaVisibility  # noqa: Y015

class _PrivacySystemMessage:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PrivacySystemMessageEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PrivacySystemMessage.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    E2EE_MSG: _PrivacySystemMessage.ValueType  # 1
    NE2EE_SELF: _PrivacySystemMessage.ValueType  # 2
    NE2EE_OTHER: _PrivacySystemMessage.ValueType  # 3

class PrivacySystemMessage(_PrivacySystemMessage, metaclass=_PrivacySystemMessageEnumTypeWrapper): ...

E2EE_MSG: PrivacySystemMessage.ValueType  # 1
NE2EE_SELF: PrivacySystemMessage.ValueType  # 2
NE2EE_OTHER: PrivacySystemMessage.ValueType  # 3
Global___PrivacySystemMessage: _TypeAlias = PrivacySystemMessage  # noqa: Y015

@_typing.final
class HistorySync(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _BotAIWaitListState:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _BotAIWaitListStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HistorySync._BotAIWaitListState.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        IN_WAITLIST: HistorySync._BotAIWaitListState.ValueType  # 0
        AI_AVAILABLE: HistorySync._BotAIWaitListState.ValueType  # 1

    class BotAIWaitListState(_BotAIWaitListState, metaclass=_BotAIWaitListStateEnumTypeWrapper): ...
    IN_WAITLIST: HistorySync.BotAIWaitListState.ValueType  # 0
    AI_AVAILABLE: HistorySync.BotAIWaitListState.ValueType  # 1

    class _HistorySyncType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _HistorySyncTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[HistorySync._HistorySyncType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        INITIAL_BOOTSTRAP: HistorySync._HistorySyncType.ValueType  # 0
        INITIAL_STATUS_V3: HistorySync._HistorySyncType.ValueType  # 1
        FULL: HistorySync._HistorySyncType.ValueType  # 2
        RECENT: HistorySync._HistorySyncType.ValueType  # 3
        PUSH_NAME: HistorySync._HistorySyncType.ValueType  # 4
        NON_BLOCKING_DATA: HistorySync._HistorySyncType.ValueType  # 5
        ON_DEMAND: HistorySync._HistorySyncType.ValueType  # 6

    class HistorySyncType(_HistorySyncType, metaclass=_HistorySyncTypeEnumTypeWrapper): ...
    INITIAL_BOOTSTRAP: HistorySync.HistorySyncType.ValueType  # 0
    INITIAL_STATUS_V3: HistorySync.HistorySyncType.ValueType  # 1
    FULL: HistorySync.HistorySyncType.ValueType  # 2
    RECENT: HistorySync.HistorySyncType.ValueType  # 3
    PUSH_NAME: HistorySync.HistorySyncType.ValueType  # 4
    NON_BLOCKING_DATA: HistorySync.HistorySyncType.ValueType  # 5
    ON_DEMAND: HistorySync.HistorySyncType.ValueType  # 6

    SYNCTYPE_FIELD_NUMBER: _builtins.int
    CONVERSATIONS_FIELD_NUMBER: _builtins.int
    STATUSV3MESSAGES_FIELD_NUMBER: _builtins.int
    CHUNKORDER_FIELD_NUMBER: _builtins.int
    PROGRESS_FIELD_NUMBER: _builtins.int
    PUSHNAMES_FIELD_NUMBER: _builtins.int
    GLOBALSETTINGS_FIELD_NUMBER: _builtins.int
    THREADIDUSERSECRET_FIELD_NUMBER: _builtins.int
    THREADDSTIMEFRAMEOFFSET_FIELD_NUMBER: _builtins.int
    RECENTSTICKERS_FIELD_NUMBER: _builtins.int
    PASTPARTICIPANTS_FIELD_NUMBER: _builtins.int
    CALLLOGRECORDS_FIELD_NUMBER: _builtins.int
    AIWAITLISTSTATE_FIELD_NUMBER: _builtins.int
    PHONENUMBERTOLIDMAPPINGS_FIELD_NUMBER: _builtins.int
    COMPANIONMETANONCE_FIELD_NUMBER: _builtins.int
    SHAREABLECHATIDENTIFIERENCRYPTIONKEY_FIELD_NUMBER: _builtins.int
    ACCOUNTS_FIELD_NUMBER: _builtins.int
    syncType: Global___HistorySync.HistorySyncType.ValueType
    chunkOrder: _builtins.int
    progress: _builtins.int
    threadIDUserSecret: _builtins.bytes
    threadDsTimeframeOffset: _builtins.int
    aiWaitListState: Global___HistorySync.BotAIWaitListState.ValueType
    companionMetaNonce: _builtins.str
    shareableChatIdentifierEncryptionKey: _builtins.bytes
    @_builtins.property
    def conversations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Conversation]: ...
    @_builtins.property
    def statusV3Messages(self) -> _containers.RepeatedCompositeFieldContainer[_WAWebProtobufsWeb_pb2.WebMessageInfo]: ...
    @_builtins.property
    def pushnames(self) -> _containers.RepeatedCompositeFieldContainer[Global___Pushname]: ...
    @_builtins.property
    def globalSettings(self) -> Global___GlobalSettings: ...
    @_builtins.property
    def recentStickers(self) -> _containers.RepeatedCompositeFieldContainer[Global___StickerMetadata]: ...
    @_builtins.property
    def pastParticipants(self) -> _containers.RepeatedCompositeFieldContainer[Global___PastParticipants]: ...
    @_builtins.property
    def callLogRecords(self) -> _containers.RepeatedCompositeFieldContainer[_WAWebProtobufSyncAction_pb2.CallLogRecord]: ...
    @_builtins.property
    def phoneNumberToLidMappings(self) -> _containers.RepeatedCompositeFieldContainer[Global___PhoneNumberToLIDMapping]: ...
    @_builtins.property
    def accounts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Account]: ...
    def __init__(
        self,
        *,
        syncType: Global___HistorySync.HistorySyncType.ValueType | None = ...,
        conversations: _abc.Iterable[Global___Conversation] | None = ...,
        statusV3Messages: _abc.Iterable[_WAWebProtobufsWeb_pb2.WebMessageInfo] | None = ...,
        chunkOrder: _builtins.int | None = ...,
        progress: _builtins.int | None = ...,
        pushnames: _abc.Iterable[Global___Pushname] | None = ...,
        globalSettings: Global___GlobalSettings | None = ...,
        threadIDUserSecret: _builtins.bytes | None = ...,
        threadDsTimeframeOffset: _builtins.int | None = ...,
        recentStickers: _abc.Iterable[Global___StickerMetadata] | None = ...,
        pastParticipants: _abc.Iterable[Global___PastParticipants] | None = ...,
        callLogRecords: _abc.Iterable[_WAWebProtobufSyncAction_pb2.CallLogRecord] | None = ...,
        aiWaitListState: Global___HistorySync.BotAIWaitListState.ValueType | None = ...,
        phoneNumberToLidMappings: _abc.Iterable[Global___PhoneNumberToLIDMapping] | None = ...,
        companionMetaNonce: _builtins.str | None = ...,
        shareableChatIdentifierEncryptionKey: _builtins.bytes | None = ...,
        accounts: _abc.Iterable[Global___Account] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["aiWaitListState", b"aiWaitListState", "chunkOrder", b"chunkOrder", "companionMetaNonce", b"companionMetaNonce", "globalSettings", b"globalSettings", "progress", b"progress", "shareableChatIdentifierEncryptionKey", b"shareableChatIdentifierEncryptionKey", "syncType", b"syncType", "threadDsTimeframeOffset", b"threadDsTimeframeOffset", "threadIDUserSecret", b"threadIDUserSecret"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accounts", b"accounts", "aiWaitListState", b"aiWaitListState", "callLogRecords", b"callLogRecords", "chunkOrder", b"chunkOrder", "companionMetaNonce", b"companionMetaNonce", "conversations", b"conversations", "globalSettings", b"globalSettings", "pastParticipants", b"pastParticipants", "phoneNumberToLidMappings", b"phoneNumberToLidMappings", "progress", b"progress", "pushnames", b"pushnames", "recentStickers", b"recentStickers", "shareableChatIdentifierEncryptionKey", b"shareableChatIdentifierEncryptionKey", "statusV3Messages", b"statusV3Messages", "syncType", b"syncType", "threadDsTimeframeOffset", b"threadDsTimeframeOffset", "threadIDUserSecret", b"threadIDUserSecret"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistorySync: _TypeAlias = HistorySync  # noqa: Y015

@_typing.final
class Conversation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _EndOfHistoryTransferType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _EndOfHistoryTransferTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Conversation._EndOfHistoryTransferType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        COMPLETE_BUT_MORE_MESSAGES_REMAIN_ON_PRIMARY: Conversation._EndOfHistoryTransferType.ValueType  # 0
        COMPLETE_AND_NO_MORE_MESSAGE_REMAIN_ON_PRIMARY: Conversation._EndOfHistoryTransferType.ValueType  # 1
        COMPLETE_ON_DEMAND_SYNC_BUT_MORE_MSG_REMAIN_ON_PRIMARY: Conversation._EndOfHistoryTransferType.ValueType  # 2
        COMPLETE_ON_DEMAND_SYNC_WITH_MORE_MSG_ON_PRIMARY_BUT_NO_ACCESS: Conversation._EndOfHistoryTransferType.ValueType  # 3

    class EndOfHistoryTransferType(_EndOfHistoryTransferType, metaclass=_EndOfHistoryTransferTypeEnumTypeWrapper): ...
    COMPLETE_BUT_MORE_MESSAGES_REMAIN_ON_PRIMARY: Conversation.EndOfHistoryTransferType.ValueType  # 0
    COMPLETE_AND_NO_MORE_MESSAGE_REMAIN_ON_PRIMARY: Conversation.EndOfHistoryTransferType.ValueType  # 1
    COMPLETE_ON_DEMAND_SYNC_BUT_MORE_MSG_REMAIN_ON_PRIMARY: Conversation.EndOfHistoryTransferType.ValueType  # 2
    COMPLETE_ON_DEMAND_SYNC_WITH_MORE_MSG_ON_PRIMARY_BUT_NO_ACCESS: Conversation.EndOfHistoryTransferType.ValueType  # 3

    ID_FIELD_NUMBER: _builtins.int
    MESSAGES_FIELD_NUMBER: _builtins.int
    NEWJID_FIELD_NUMBER: _builtins.int
    OLDJID_FIELD_NUMBER: _builtins.int
    LASTMSGTIMESTAMP_FIELD_NUMBER: _builtins.int
    UNREADCOUNT_FIELD_NUMBER: _builtins.int
    READONLY_FIELD_NUMBER: _builtins.int
    ENDOFHISTORYTRANSFER_FIELD_NUMBER: _builtins.int
    EPHEMERALEXPIRATION_FIELD_NUMBER: _builtins.int
    EPHEMERALSETTINGTIMESTAMP_FIELD_NUMBER: _builtins.int
    ENDOFHISTORYTRANSFERTYPE_FIELD_NUMBER: _builtins.int
    CONVERSATIONTIMESTAMP_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    PHASH_FIELD_NUMBER: _builtins.int
    NOTSPAM_FIELD_NUMBER: _builtins.int
    ARCHIVED_FIELD_NUMBER: _builtins.int
    DISAPPEARINGMODE_FIELD_NUMBER: _builtins.int
    UNREADMENTIONCOUNT_FIELD_NUMBER: _builtins.int
    MARKEDASUNREAD_FIELD_NUMBER: _builtins.int
    PARTICIPANT_FIELD_NUMBER: _builtins.int
    TCTOKEN_FIELD_NUMBER: _builtins.int
    TCTOKENTIMESTAMP_FIELD_NUMBER: _builtins.int
    CONTACTPRIMARYIDENTITYKEY_FIELD_NUMBER: _builtins.int
    PINNED_FIELD_NUMBER: _builtins.int
    MUTEENDTIME_FIELD_NUMBER: _builtins.int
    WALLPAPER_FIELD_NUMBER: _builtins.int
    MEDIAVISIBILITY_FIELD_NUMBER: _builtins.int
    TCTOKENSENDERTIMESTAMP_FIELD_NUMBER: _builtins.int
    SUSPENDED_FIELD_NUMBER: _builtins.int
    TERMINATED_FIELD_NUMBER: _builtins.int
    CREATEDAT_FIELD_NUMBER: _builtins.int
    CREATEDBY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    SUPPORT_FIELD_NUMBER: _builtins.int
    ISPARENTGROUP_FIELD_NUMBER: _builtins.int
    PARENTGROUPID_FIELD_NUMBER: _builtins.int
    ISDEFAULTSUBGROUP_FIELD_NUMBER: _builtins.int
    DISPLAYNAME_FIELD_NUMBER: _builtins.int
    PNJID_FIELD_NUMBER: _builtins.int
    SHAREOWNPN_FIELD_NUMBER: _builtins.int
    PNHDUPLICATELIDTHREAD_FIELD_NUMBER: _builtins.int
    LIDJID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    LIDORIGINTYPE_FIELD_NUMBER: _builtins.int
    COMMENTSCOUNT_FIELD_NUMBER: _builtins.int
    LOCKED_FIELD_NUMBER: _builtins.int
    SYSTEMMESSAGETOINSERT_FIELD_NUMBER: _builtins.int
    CAPICREATEDGROUP_FIELD_NUMBER: _builtins.int
    ACCOUNTLID_FIELD_NUMBER: _builtins.int
    LIMITSHARING_FIELD_NUMBER: _builtins.int
    LIMITSHARINGSETTINGTIMESTAMP_FIELD_NUMBER: _builtins.int
    LIMITSHARINGTRIGGER_FIELD_NUMBER: _builtins.int
    LIMITSHARINGINITIATEDBYME_FIELD_NUMBER: _builtins.int
    MAIBAAITHREADENABLED_FIELD_NUMBER: _builtins.int
    ID: _builtins.str
    newJID: _builtins.str
    oldJID: _builtins.str
    lastMsgTimestamp: _builtins.int
    unreadCount: _builtins.int
    readOnly: _builtins.bool
    endOfHistoryTransfer: _builtins.bool
    ephemeralExpiration: _builtins.int
    ephemeralSettingTimestamp: _builtins.int
    endOfHistoryTransferType: Global___Conversation.EndOfHistoryTransferType.ValueType
    conversationTimestamp: _builtins.int
    name: _builtins.str
    pHash: _builtins.str
    notSpam: _builtins.bool
    archived: _builtins.bool
    unreadMentionCount: _builtins.int
    markedAsUnread: _builtins.bool
    tcToken: _builtins.bytes
    tcTokenTimestamp: _builtins.int
    contactPrimaryIdentityKey: _builtins.bytes
    pinned: _builtins.int
    muteEndTime: _builtins.int
    mediaVisibility: Global___MediaVisibility.ValueType
    tcTokenSenderTimestamp: _builtins.int
    suspended: _builtins.bool
    terminated: _builtins.bool
    createdAt: _builtins.int
    createdBy: _builtins.str
    description: _builtins.str
    support: _builtins.bool
    isParentGroup: _builtins.bool
    parentGroupID: _builtins.str
    isDefaultSubgroup: _builtins.bool
    displayName: _builtins.str
    pnJID: _builtins.str
    shareOwnPn: _builtins.bool
    pnhDuplicateLidThread: _builtins.bool
    lidJID: _builtins.str
    username: _builtins.str
    lidOriginType: _builtins.str
    commentsCount: _builtins.int
    locked: _builtins.bool
    systemMessageToInsert: Global___PrivacySystemMessage.ValueType
    capiCreatedGroup: _builtins.bool
    accountLid: _builtins.str
    limitSharing: _builtins.bool
    limitSharingSettingTimestamp: _builtins.int
    limitSharingTrigger: _WACommon_pb2.LimitSharing.Trigger.ValueType
    limitSharingInitiatedByMe: _builtins.bool
    maibaAiThreadEnabled: _builtins.bool
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[Global___HistorySyncMsg]: ...
    @_builtins.property
    def disappearingMode(self) -> _WAWebProtobufsE2E_pb2.DisappearingMode: ...
    @_builtins.property
    def participant(self) -> _containers.RepeatedCompositeFieldContainer[Global___GroupParticipant]: ...
    @_builtins.property
    def wallpaper(self) -> Global___WallpaperSettings: ...
    def __init__(
        self,
        *,
        ID: _builtins.str | None = ...,
        messages: _abc.Iterable[Global___HistorySyncMsg] | None = ...,
        newJID: _builtins.str | None = ...,
        oldJID: _builtins.str | None = ...,
        lastMsgTimestamp: _builtins.int | None = ...,
        unreadCount: _builtins.int | None = ...,
        readOnly: _builtins.bool | None = ...,
        endOfHistoryTransfer: _builtins.bool | None = ...,
        ephemeralExpiration: _builtins.int | None = ...,
        ephemeralSettingTimestamp: _builtins.int | None = ...,
        endOfHistoryTransferType: Global___Conversation.EndOfHistoryTransferType.ValueType | None = ...,
        conversationTimestamp: _builtins.int | None = ...,
        name: _builtins.str | None = ...,
        pHash: _builtins.str | None = ...,
        notSpam: _builtins.bool | None = ...,
        archived: _builtins.bool | None = ...,
        disappearingMode: _WAWebProtobufsE2E_pb2.DisappearingMode | None = ...,
        unreadMentionCount: _builtins.int | None = ...,
        markedAsUnread: _builtins.bool | None = ...,
        participant: _abc.Iterable[Global___GroupParticipant] | None = ...,
        tcToken: _builtins.bytes | None = ...,
        tcTokenTimestamp: _builtins.int | None = ...,
        contactPrimaryIdentityKey: _builtins.bytes | None = ...,
        pinned: _builtins.int | None = ...,
        muteEndTime: _builtins.int | None = ...,
        wallpaper: Global___WallpaperSettings | None = ...,
        mediaVisibility: Global___MediaVisibility.ValueType | None = ...,
        tcTokenSenderTimestamp: _builtins.int | None = ...,
        suspended: _builtins.bool | None = ...,
        terminated: _builtins.bool | None = ...,
        createdAt: _builtins.int | None = ...,
        createdBy: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        support: _builtins.bool | None = ...,
        isParentGroup: _builtins.bool | None = ...,
        parentGroupID: _builtins.str | None = ...,
        isDefaultSubgroup: _builtins.bool | None = ...,
        displayName: _builtins.str | None = ...,
        pnJID: _builtins.str | None = ...,
        shareOwnPn: _builtins.bool | None = ...,
        pnhDuplicateLidThread: _builtins.bool | None = ...,
        lidJID: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
        lidOriginType: _builtins.str | None = ...,
        commentsCount: _builtins.int | None = ...,
        locked: _builtins.bool | None = ...,
        systemMessageToInsert: Global___PrivacySystemMessage.ValueType | None = ...,
        capiCreatedGroup: _builtins.bool | None = ...,
        accountLid: _builtins.str | None = ...,
        limitSharing: _builtins.bool | None = ...,
        limitSharingSettingTimestamp: _builtins.int | None = ...,
        limitSharingTrigger: _WACommon_pb2.LimitSharing.Trigger.ValueType | None = ...,
        limitSharingInitiatedByMe: _builtins.bool | None = ...,
        maibaAiThreadEnabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ID", b"ID", "accountLid", b"accountLid", "archived", b"archived", "capiCreatedGroup", b"capiCreatedGroup", "commentsCount", b"commentsCount", "contactPrimaryIdentityKey", b"contactPrimaryIdentityKey", "conversationTimestamp", b"conversationTimestamp", "createdAt", b"createdAt", "createdBy", b"createdBy", "description", b"description", "disappearingMode", b"disappearingMode", "displayName", b"displayName", "endOfHistoryTransfer", b"endOfHistoryTransfer", "endOfHistoryTransferType", b"endOfHistoryTransferType", "ephemeralExpiration", b"ephemeralExpiration", "ephemeralSettingTimestamp", b"ephemeralSettingTimestamp", "isDefaultSubgroup", b"isDefaultSubgroup", "isParentGroup", b"isParentGroup", "lastMsgTimestamp", b"lastMsgTimestamp", "lidJID", b"lidJID", "lidOriginType", b"lidOriginType", "limitSharing", b"limitSharing", "limitSharingInitiatedByMe", b"limitSharingInitiatedByMe", "limitSharingSettingTimestamp", b"limitSharingSettingTimestamp", "limitSharingTrigger", b"limitSharingTrigger", "locked", b"locked", "maibaAiThreadEnabled", b"maibaAiThreadEnabled", "markedAsUnread", b"markedAsUnread", "mediaVisibility", b"mediaVisibility", "muteEndTime", b"muteEndTime", "name", b"name", "newJID", b"newJID", "notSpam", b"notSpam", "oldJID", b"oldJID", "pHash", b"pHash", "parentGroupID", b"parentGroupID", "pinned", b"pinned", "pnJID", b"pnJID", "pnhDuplicateLidThread", b"pnhDuplicateLidThread", "readOnly", b"readOnly", "shareOwnPn", b"shareOwnPn", "support", b"support", "suspended", b"suspended", "systemMessageToInsert", b"systemMessageToInsert", "tcToken", b"tcToken", "tcTokenSenderTimestamp", b"tcTokenSenderTimestamp", "tcTokenTimestamp", b"tcTokenTimestamp", "terminated", b"terminated", "unreadCount", b"unreadCount", "unreadMentionCount", b"unreadMentionCount", "username", b"username", "wallpaper", b"wallpaper"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ID", b"ID", "accountLid", b"accountLid", "archived", b"archived", "capiCreatedGroup", b"capiCreatedGroup", "commentsCount", b"commentsCount", "contactPrimaryIdentityKey", b"contactPrimaryIdentityKey", "conversationTimestamp", b"conversationTimestamp", "createdAt", b"createdAt", "createdBy", b"createdBy", "description", b"description", "disappearingMode", b"disappearingMode", "displayName", b"displayName", "endOfHistoryTransfer", b"endOfHistoryTransfer", "endOfHistoryTransferType", b"endOfHistoryTransferType", "ephemeralExpiration", b"ephemeralExpiration", "ephemeralSettingTimestamp", b"ephemeralSettingTimestamp", "isDefaultSubgroup", b"isDefaultSubgroup", "isParentGroup", b"isParentGroup", "lastMsgTimestamp", b"lastMsgTimestamp", "lidJID", b"lidJID", "lidOriginType", b"lidOriginType", "limitSharing", b"limitSharing", "limitSharingInitiatedByMe", b"limitSharingInitiatedByMe", "limitSharingSettingTimestamp", b"limitSharingSettingTimestamp", "limitSharingTrigger", b"limitSharingTrigger", "locked", b"locked", "maibaAiThreadEnabled", b"maibaAiThreadEnabled", "markedAsUnread", b"markedAsUnread", "mediaVisibility", b"mediaVisibility", "messages", b"messages", "muteEndTime", b"muteEndTime", "name", b"name", "newJID", b"newJID", "notSpam", b"notSpam", "oldJID", b"oldJID", "pHash", b"pHash", "parentGroupID", b"parentGroupID", "participant", b"participant", "pinned", b"pinned", "pnJID", b"pnJID", "pnhDuplicateLidThread", b"pnhDuplicateLidThread", "readOnly", b"readOnly", "shareOwnPn", b"shareOwnPn", "support", b"support", "suspended", b"suspended", "systemMessageToInsert", b"systemMessageToInsert", "tcToken", b"tcToken", "tcTokenSenderTimestamp", b"tcTokenSenderTimestamp", "tcTokenTimestamp", b"tcTokenTimestamp", "terminated", b"terminated", "unreadCount", b"unreadCount", "unreadMentionCount", b"unreadMentionCount", "username", b"username", "wallpaper", b"wallpaper"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Conversation: _TypeAlias = Conversation  # noqa: Y015

@_typing.final
class GroupParticipant(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Rank:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _RankEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[GroupParticipant._Rank.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        REGULAR: GroupParticipant._Rank.ValueType  # 0
        ADMIN: GroupParticipant._Rank.ValueType  # 1
        SUPERADMIN: GroupParticipant._Rank.ValueType  # 2

    class Rank(_Rank, metaclass=_RankEnumTypeWrapper): ...
    REGULAR: GroupParticipant.Rank.ValueType  # 0
    ADMIN: GroupParticipant.Rank.ValueType  # 1
    SUPERADMIN: GroupParticipant.Rank.ValueType  # 2

    USERJID_FIELD_NUMBER: _builtins.int
    RANK_FIELD_NUMBER: _builtins.int
    MEMBERLABEL_FIELD_NUMBER: _builtins.int
    userJID: _builtins.str
    rank: Global___GroupParticipant.Rank.ValueType
    @_builtins.property
    def memberLabel(self) -> _WAWebProtobufsE2E_pb2.MemberLabel: ...
    def __init__(
        self,
        *,
        userJID: _builtins.str | None = ...,
        rank: Global___GroupParticipant.Rank.ValueType | None = ...,
        memberLabel: _WAWebProtobufsE2E_pb2.MemberLabel | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["memberLabel", b"memberLabel", "rank", b"rank", "userJID", b"userJID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["memberLabel", b"memberLabel", "rank", b"rank", "userJID", b"userJID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GroupParticipant: _TypeAlias = GroupParticipant  # noqa: Y015

@_typing.final
class PastParticipant(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _LeaveReason:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LeaveReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PastParticipant._LeaveReason.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEFT: PastParticipant._LeaveReason.ValueType  # 0
        REMOVED: PastParticipant._LeaveReason.ValueType  # 1

    class LeaveReason(_LeaveReason, metaclass=_LeaveReasonEnumTypeWrapper): ...
    LEFT: PastParticipant.LeaveReason.ValueType  # 0
    REMOVED: PastParticipant.LeaveReason.ValueType  # 1

    USERJID_FIELD_NUMBER: _builtins.int
    LEAVEREASON_FIELD_NUMBER: _builtins.int
    LEAVETS_FIELD_NUMBER: _builtins.int
    userJID: _builtins.str
    leaveReason: Global___PastParticipant.LeaveReason.ValueType
    leaveTS: _builtins.int
    def __init__(
        self,
        *,
        userJID: _builtins.str | None = ...,
        leaveReason: Global___PastParticipant.LeaveReason.ValueType | None = ...,
        leaveTS: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["leaveReason", b"leaveReason", "leaveTS", b"leaveTS", "userJID", b"userJID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["leaveReason", b"leaveReason", "leaveTS", b"leaveTS", "userJID", b"userJID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PastParticipant: _TypeAlias = PastParticipant  # noqa: Y015

@_typing.final
class PhoneNumberToLIDMapping(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PNJID_FIELD_NUMBER: _builtins.int
    LIDJID_FIELD_NUMBER: _builtins.int
    pnJID: _builtins.str
    lidJID: _builtins.str
    def __init__(
        self,
        *,
        pnJID: _builtins.str | None = ...,
        lidJID: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lidJID", b"lidJID", "pnJID", b"pnJID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lidJID", b"lidJID", "pnJID", b"pnJID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PhoneNumberToLIDMapping: _TypeAlias = PhoneNumberToLIDMapping  # noqa: Y015

@_typing.final
class Account(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    COUNTRYCODE_FIELD_NUMBER: _builtins.int
    ISUSERNAMEDELETED_FIELD_NUMBER: _builtins.int
    lid: _builtins.str
    username: _builtins.str
    countryCode: _builtins.str
    isUsernameDeleted: _builtins.bool
    def __init__(
        self,
        *,
        lid: _builtins.str | None = ...,
        username: _builtins.str | None = ...,
        countryCode: _builtins.str | None = ...,
        isUsernameDeleted: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["countryCode", b"countryCode", "isUsernameDeleted", b"isUsernameDeleted", "lid", b"lid", "username", b"username"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countryCode", b"countryCode", "isUsernameDeleted", b"isUsernameDeleted", "lid", b"lid", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Account: _TypeAlias = Account  # noqa: Y015

@_typing.final
class HistorySyncMsg(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    MSGORDERID_FIELD_NUMBER: _builtins.int
    msgOrderID: _builtins.int
    @_builtins.property
    def message(self) -> _WAWebProtobufsWeb_pb2.WebMessageInfo: ...
    def __init__(
        self,
        *,
        message: _WAWebProtobufsWeb_pb2.WebMessageInfo | None = ...,
        msgOrderID: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "msgOrderID", b"msgOrderID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "msgOrderID", b"msgOrderID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistorySyncMsg: _TypeAlias = HistorySyncMsg  # noqa: Y015

@_typing.final
class Pushname(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PUSHNAME_FIELD_NUMBER: _builtins.int
    ID: _builtins.str
    pushname: _builtins.str
    def __init__(
        self,
        *,
        ID: _builtins.str | None = ...,
        pushname: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ID", b"ID", "pushname", b"pushname"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ID", b"ID", "pushname", b"pushname"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Pushname: _TypeAlias = Pushname  # noqa: Y015

@_typing.final
class WallpaperSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILENAME_FIELD_NUMBER: _builtins.int
    OPACITY_FIELD_NUMBER: _builtins.int
    filename: _builtins.str
    opacity: _builtins.int
    def __init__(
        self,
        *,
        filename: _builtins.str | None = ...,
        opacity: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "opacity", b"opacity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "opacity", b"opacity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WallpaperSettings: _TypeAlias = WallpaperSettings  # noqa: Y015

@_typing.final
class GlobalSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIGHTTHEMEWALLPAPER_FIELD_NUMBER: _builtins.int
    MEDIAVISIBILITY_FIELD_NUMBER: _builtins.int
    DARKTHEMEWALLPAPER_FIELD_NUMBER: _builtins.int
    AUTODOWNLOADWIFI_FIELD_NUMBER: _builtins.int
    AUTODOWNLOADCELLULAR_FIELD_NUMBER: _builtins.int
    AUTODOWNLOADROAMING_FIELD_NUMBER: _builtins.int
    SHOWINDIVIDUALNOTIFICATIONSPREVIEW_FIELD_NUMBER: _builtins.int
    SHOWGROUPNOTIFICATIONSPREVIEW_FIELD_NUMBER: _builtins.int
    DISAPPEARINGMODEDURATION_FIELD_NUMBER: _builtins.int
    DISAPPEARINGMODETIMESTAMP_FIELD_NUMBER: _builtins.int
    AVATARUSERSETTINGS_FIELD_NUMBER: _builtins.int
    FONTSIZE_FIELD_NUMBER: _builtins.int
    SECURITYNOTIFICATIONS_FIELD_NUMBER: _builtins.int
    AUTOUNARCHIVECHATS_FIELD_NUMBER: _builtins.int
    VIDEOQUALITYMODE_FIELD_NUMBER: _builtins.int
    PHOTOQUALITYMODE_FIELD_NUMBER: _builtins.int
    INDIVIDUALNOTIFICATIONSETTINGS_FIELD_NUMBER: _builtins.int
    GROUPNOTIFICATIONSETTINGS_FIELD_NUMBER: _builtins.int
    CHATLOCKSETTINGS_FIELD_NUMBER: _builtins.int
    CHATDBLIDMIGRATIONTIMESTAMP_FIELD_NUMBER: _builtins.int
    mediaVisibility: Global___MediaVisibility.ValueType
    showIndividualNotificationsPreview: _builtins.bool
    showGroupNotificationsPreview: _builtins.bool
    disappearingModeDuration: _builtins.int
    disappearingModeTimestamp: _builtins.int
    fontSize: _builtins.int
    securityNotifications: _builtins.bool
    autoUnarchiveChats: _builtins.bool
    videoQualityMode: _builtins.int
    photoQualityMode: _builtins.int
    chatDbLidMigrationTimestamp: _builtins.int
    @_builtins.property
    def lightThemeWallpaper(self) -> Global___WallpaperSettings: ...
    @_builtins.property
    def darkThemeWallpaper(self) -> Global___WallpaperSettings: ...
    @_builtins.property
    def autoDownloadWiFi(self) -> Global___AutoDownloadSettings: ...
    @_builtins.property
    def autoDownloadCellular(self) -> Global___AutoDownloadSettings: ...
    @_builtins.property
    def autoDownloadRoaming(self) -> Global___AutoDownloadSettings: ...
    @_builtins.property
    def avatarUserSettings(self) -> Global___AvatarUserSettings: ...
    @_builtins.property
    def individualNotificationSettings(self) -> Global___NotificationSettings: ...
    @_builtins.property
    def groupNotificationSettings(self) -> Global___NotificationSettings: ...
    @_builtins.property
    def chatLockSettings(self) -> _WAWebProtobufsChatLockSettings_pb2.ChatLockSettings: ...
    def __init__(
        self,
        *,
        lightThemeWallpaper: Global___WallpaperSettings | None = ...,
        mediaVisibility: Global___MediaVisibility.ValueType | None = ...,
        darkThemeWallpaper: Global___WallpaperSettings | None = ...,
        autoDownloadWiFi: Global___AutoDownloadSettings | None = ...,
        autoDownloadCellular: Global___AutoDownloadSettings | None = ...,
        autoDownloadRoaming: Global___AutoDownloadSettings | None = ...,
        showIndividualNotificationsPreview: _builtins.bool | None = ...,
        showGroupNotificationsPreview: _builtins.bool | None = ...,
        disappearingModeDuration: _builtins.int | None = ...,
        disappearingModeTimestamp: _builtins.int | None = ...,
        avatarUserSettings: Global___AvatarUserSettings | None = ...,
        fontSize: _builtins.int | None = ...,
        securityNotifications: _builtins.bool | None = ...,
        autoUnarchiveChats: _builtins.bool | None = ...,
        videoQualityMode: _builtins.int | None = ...,
        photoQualityMode: _builtins.int | None = ...,
        individualNotificationSettings: Global___NotificationSettings | None = ...,
        groupNotificationSettings: Global___NotificationSettings | None = ...,
        chatLockSettings: _WAWebProtobufsChatLockSettings_pb2.ChatLockSettings | None = ...,
        chatDbLidMigrationTimestamp: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["autoDownloadCellular", b"autoDownloadCellular", "autoDownloadRoaming", b"autoDownloadRoaming", "autoDownloadWiFi", b"autoDownloadWiFi", "autoUnarchiveChats", b"autoUnarchiveChats", "avatarUserSettings", b"avatarUserSettings", "chatDbLidMigrationTimestamp", b"chatDbLidMigrationTimestamp", "chatLockSettings", b"chatLockSettings", "darkThemeWallpaper", b"darkThemeWallpaper", "disappearingModeDuration", b"disappearingModeDuration", "disappearingModeTimestamp", b"disappearingModeTimestamp", "fontSize", b"fontSize", "groupNotificationSettings", b"groupNotificationSettings", "individualNotificationSettings", b"individualNotificationSettings", "lightThemeWallpaper", b"lightThemeWallpaper", "mediaVisibility", b"mediaVisibility", "photoQualityMode", b"photoQualityMode", "securityNotifications", b"securityNotifications", "showGroupNotificationsPreview", b"showGroupNotificationsPreview", "showIndividualNotificationsPreview", b"showIndividualNotificationsPreview", "videoQualityMode", b"videoQualityMode"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["autoDownloadCellular", b"autoDownloadCellular", "autoDownloadRoaming", b"autoDownloadRoaming", "autoDownloadWiFi", b"autoDownloadWiFi", "autoUnarchiveChats", b"autoUnarchiveChats", "avatarUserSettings", b"avatarUserSettings", "chatDbLidMigrationTimestamp", b"chatDbLidMigrationTimestamp", "chatLockSettings", b"chatLockSettings", "darkThemeWallpaper", b"darkThemeWallpaper", "disappearingModeDuration", b"disappearingModeDuration", "disappearingModeTimestamp", b"disappearingModeTimestamp", "fontSize", b"fontSize", "groupNotificationSettings", b"groupNotificationSettings", "individualNotificationSettings", b"individualNotificationSettings", "lightThemeWallpaper", b"lightThemeWallpaper", "mediaVisibility", b"mediaVisibility", "photoQualityMode", b"photoQualityMode", "securityNotifications", b"securityNotifications", "showGroupNotificationsPreview", b"showGroupNotificationsPreview", "showIndividualNotificationsPreview", b"showIndividualNotificationsPreview", "videoQualityMode", b"videoQualityMode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GlobalSettings: _TypeAlias = GlobalSettings  # noqa: Y015

@_typing.final
class AutoDownloadSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOWNLOADIMAGES_FIELD_NUMBER: _builtins.int
    DOWNLOADAUDIO_FIELD_NUMBER: _builtins.int
    DOWNLOADVIDEO_FIELD_NUMBER: _builtins.int
    DOWNLOADDOCUMENTS_FIELD_NUMBER: _builtins.int
    downloadImages: _builtins.bool
    downloadAudio: _builtins.bool
    downloadVideo: _builtins.bool
    downloadDocuments: _builtins.bool
    def __init__(
        self,
        *,
        downloadImages: _builtins.bool | None = ...,
        downloadAudio: _builtins.bool | None = ...,
        downloadVideo: _builtins.bool | None = ...,
        downloadDocuments: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["downloadAudio", b"downloadAudio", "downloadDocuments", b"downloadDocuments", "downloadImages", b"downloadImages", "downloadVideo", b"downloadVideo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["downloadAudio", b"downloadAudio", "downloadDocuments", b"downloadDocuments", "downloadImages", b"downloadImages", "downloadVideo", b"downloadVideo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AutoDownloadSettings: _TypeAlias = AutoDownloadSettings  # noqa: Y015

@_typing.final
class StickerMetadata(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    FILESHA256_FIELD_NUMBER: _builtins.int
    FILEENCSHA256_FIELD_NUMBER: _builtins.int
    MEDIAKEY_FIELD_NUMBER: _builtins.int
    MIMETYPE_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    DIRECTPATH_FIELD_NUMBER: _builtins.int
    FILELENGTH_FIELD_NUMBER: _builtins.int
    WEIGHT_FIELD_NUMBER: _builtins.int
    LASTSTICKERSENTTS_FIELD_NUMBER: _builtins.int
    ISLOTTIE_FIELD_NUMBER: _builtins.int
    IMAGEHASH_FIELD_NUMBER: _builtins.int
    ISAVATARSTICKER_FIELD_NUMBER: _builtins.int
    URL: _builtins.str
    fileSHA256: _builtins.bytes
    fileEncSHA256: _builtins.bytes
    mediaKey: _builtins.bytes
    mimetype: _builtins.str
    height: _builtins.int
    width: _builtins.int
    directPath: _builtins.str
    fileLength: _builtins.int
    weight: _builtins.float
    lastStickerSentTS: _builtins.int
    isLottie: _builtins.bool
    imageHash: _builtins.str
    isAvatarSticker: _builtins.bool
    def __init__(
        self,
        *,
        URL: _builtins.str | None = ...,
        fileSHA256: _builtins.bytes | None = ...,
        fileEncSHA256: _builtins.bytes | None = ...,
        mediaKey: _builtins.bytes | None = ...,
        mimetype: _builtins.str | None = ...,
        height: _builtins.int | None = ...,
        width: _builtins.int | None = ...,
        directPath: _builtins.str | None = ...,
        fileLength: _builtins.int | None = ...,
        weight: _builtins.float | None = ...,
        lastStickerSentTS: _builtins.int | None = ...,
        isLottie: _builtins.bool | None = ...,
        imageHash: _builtins.str | None = ...,
        isAvatarSticker: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["URL", b"URL", "directPath", b"directPath", "fileEncSHA256", b"fileEncSHA256", "fileLength", b"fileLength", "fileSHA256", b"fileSHA256", "height", b"height", "imageHash", b"imageHash", "isAvatarSticker", b"isAvatarSticker", "isLottie", b"isLottie", "lastStickerSentTS", b"lastStickerSentTS", "mediaKey", b"mediaKey", "mimetype", b"mimetype", "weight", b"weight", "width", b"width"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["URL", b"URL", "directPath", b"directPath", "fileEncSHA256", b"fileEncSHA256", "fileLength", b"fileLength", "fileSHA256", b"fileSHA256", "height", b"height", "imageHash", b"imageHash", "isAvatarSticker", b"isAvatarSticker", "isLottie", b"isLottie", "lastStickerSentTS", b"lastStickerSentTS", "mediaKey", b"mediaKey", "mimetype", b"mimetype", "weight", b"weight", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StickerMetadata: _TypeAlias = StickerMetadata  # noqa: Y015

@_typing.final
class PastParticipants(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GROUPJID_FIELD_NUMBER: _builtins.int
    PASTPARTICIPANTS_FIELD_NUMBER: _builtins.int
    groupJID: _builtins.str
    @_builtins.property
    def pastParticipants(self) -> _containers.RepeatedCompositeFieldContainer[Global___PastParticipant]: ...
    def __init__(
        self,
        *,
        groupJID: _builtins.str | None = ...,
        pastParticipants: _abc.Iterable[Global___PastParticipant] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["groupJID", b"groupJID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["groupJID", b"groupJID", "pastParticipants", b"pastParticipants"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PastParticipants: _TypeAlias = PastParticipants  # noqa: Y015

@_typing.final
class AvatarUserSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FBID_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    FBID: _builtins.str
    password: _builtins.str
    def __init__(
        self,
        *,
        FBID: _builtins.str | None = ...,
        password: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["FBID", b"FBID", "password", b"password"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["FBID", b"FBID", "password", b"password"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AvatarUserSettings: _TypeAlias = AvatarUserSettings  # noqa: Y015

@_typing.final
class NotificationSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGEVIBRATE_FIELD_NUMBER: _builtins.int
    MESSAGEPOPUP_FIELD_NUMBER: _builtins.int
    MESSAGELIGHT_FIELD_NUMBER: _builtins.int
    LOWPRIORITYNOTIFICATIONS_FIELD_NUMBER: _builtins.int
    REACTIONSMUTED_FIELD_NUMBER: _builtins.int
    CALLVIBRATE_FIELD_NUMBER: _builtins.int
    messageVibrate: _builtins.str
    messagePopup: _builtins.str
    messageLight: _builtins.str
    lowPriorityNotifications: _builtins.bool
    reactionsMuted: _builtins.bool
    callVibrate: _builtins.str
    def __init__(
        self,
        *,
        messageVibrate: _builtins.str | None = ...,
        messagePopup: _builtins.str | None = ...,
        messageLight: _builtins.str | None = ...,
        lowPriorityNotifications: _builtins.bool | None = ...,
        reactionsMuted: _builtins.bool | None = ...,
        callVibrate: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["callVibrate", b"callVibrate", "lowPriorityNotifications", b"lowPriorityNotifications", "messageLight", b"messageLight", "messagePopup", b"messagePopup", "messageVibrate", b"messageVibrate", "reactionsMuted", b"reactionsMuted"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["callVibrate", b"callVibrate", "lowPriorityNotifications", b"lowPriorityNotifications", "messageLight", b"messageLight", "messagePopup", b"messagePopup", "messageVibrate", b"messageVibrate", "reactionsMuted", b"reactionsMuted"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___NotificationSettings: _TypeAlias = NotificationSettings  # noqa: Y015
