"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateBackupInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECOVERYCODE_FIELD_NUMBER: _builtins.int
    USERID_FIELD_NUMBER: _builtins.int
    recoveryCode: _builtins.str
    userID: _builtins.int
    def __init__(
        self,
        *,
        recoveryCode: _builtins.str | None = ...,
        userID: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["recoveryCode", b"recoveryCode", "userID", b"userID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recoveryCode", b"recoveryCode", "userID", b"userID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateBackupInput: _TypeAlias = CreateBackupInput  # noqa: Y015

@_typing.final
class EncryptMessageInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EPOCHROOTKEY_FIELD_NUMBER: _builtins.int
    MAILBOXROOTKEY_FIELD_NUMBER: _builtins.int
    ORFCLIENTSTATE_FIELD_NUMBER: _builtins.int
    EPOCHANONID_FIELD_NUMBER: _builtins.int
    EPOCHID_FIELD_NUMBER: _builtins.int
    THREADID_FIELD_NUMBER: _builtins.int
    WACANONICALUSERFBID_FIELD_NUMBER: _builtins.int
    TIMESTAMPMS_FIELD_NUMBER: _builtins.int
    BACKUPID_FIELD_NUMBER: _builtins.int
    PLAINTEXTPAYLOAD_FIELD_NUMBER: _builtins.int
    STANZAID_FIELD_NUMBER: _builtins.int
    epochRootKey: _builtins.bytes
    mailboxRootKey: _builtins.bytes
    orfClientState: _builtins.bytes
    epochAnonID: _builtins.bytes
    epochID: _builtins.int
    threadID: _builtins.str
    waCanonicalUserFbid: _builtins.int
    timestampMS: _builtins.int
    backupID: _builtins.int
    plaintextPayload: _builtins.bytes
    stanzaID: _builtins.str
    def __init__(
        self,
        *,
        epochRootKey: _builtins.bytes | None = ...,
        mailboxRootKey: _builtins.bytes | None = ...,
        orfClientState: _builtins.bytes | None = ...,
        epochAnonID: _builtins.bytes | None = ...,
        epochID: _builtins.int | None = ...,
        threadID: _builtins.str | None = ...,
        waCanonicalUserFbid: _builtins.int | None = ...,
        timestampMS: _builtins.int | None = ...,
        backupID: _builtins.int | None = ...,
        plaintextPayload: _builtins.bytes | None = ...,
        stanzaID: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["backupID", b"backupID", "epochAnonID", b"epochAnonID", "epochID", b"epochID", "epochRootKey", b"epochRootKey", "mailboxRootKey", b"mailboxRootKey", "orfClientState", b"orfClientState", "plaintextPayload", b"plaintextPayload", "stanzaID", b"stanzaID", "threadID", b"threadID", "timestampMS", b"timestampMS", "waCanonicalUserFbid", b"waCanonicalUserFbid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backupID", b"backupID", "epochAnonID", b"epochAnonID", "epochID", b"epochID", "epochRootKey", b"epochRootKey", "mailboxRootKey", b"mailboxRootKey", "orfClientState", b"orfClientState", "plaintextPayload", b"plaintextPayload", "stanzaID", b"stanzaID", "threadID", b"threadID", "timestampMS", b"timestampMS", "waCanonicalUserFbid", b"waCanonicalUserFbid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EncryptMessageInput: _TypeAlias = EncryptMessageInput  # noqa: Y015

@_typing.final
class DecryptMessageInput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EPOCHROOTKEY_FIELD_NUMBER: _builtins.int
    EPOCHANONID_FIELD_NUMBER: _builtins.int
    THREADID_FIELD_NUMBER: _builtins.int
    ENCRYPTIONVERSION_FIELD_NUMBER: _builtins.int
    CIPHERTEXT_FIELD_NUMBER: _builtins.int
    epochRootKey: _builtins.bytes
    epochAnonID: _builtins.bytes
    threadID: _builtins.str
    encryptionVersion: _builtins.int
    ciphertext: _builtins.bytes
    def __init__(
        self,
        *,
        epochRootKey: _builtins.bytes | None = ...,
        epochAnonID: _builtins.bytes | None = ...,
        threadID: _builtins.str | None = ...,
        encryptionVersion: _builtins.int | None = ...,
        ciphertext: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ciphertext", b"ciphertext", "encryptionVersion", b"encryptionVersion", "epochAnonID", b"epochAnonID", "epochRootKey", b"epochRootKey", "threadID", b"threadID"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ciphertext", b"ciphertext", "encryptionVersion", b"encryptionVersion", "epochAnonID", b"epochAnonID", "epochRootKey", b"epochRootKey", "threadID", b"threadID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DecryptMessageInput: _TypeAlias = DecryptMessageInput  # noqa: Y015

@_typing.final
class DeviceOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUBLICKEY_FIELD_NUMBER: _builtins.int
    EPOCHAUTHPUBLICKEY_FIELD_NUMBER: _builtins.int
    EPOCHAUTHPUBLICKEYSIG_FIELD_NUMBER: _builtins.int
    EPOCHSTORAGEPUBLICKEY_FIELD_NUMBER: _builtins.int
    EPOCHSTORAGEPUBLICKEYSIG_FIELD_NUMBER: _builtins.int
    SUPPORTEDENCRYPTIONVERSIONS_FIELD_NUMBER: _builtins.int
    ENCRYPTIONVERSIONSIGNATURE_FIELD_NUMBER: _builtins.int
    CLIENTVERSION_FIELD_NUMBER: _builtins.int
    OCMFCLIENTSTATE_FIELD_NUMBER: _builtins.int
    publicKey: _builtins.bytes
    epochAuthPublicKey: _builtins.bytes
    epochAuthPublicKeySig: _builtins.bytes
    epochStoragePublicKey: _builtins.bytes
    epochStoragePublicKeySig: _builtins.bytes
    encryptionVersionSignature: _builtins.bytes
    clientVersion: _builtins.int
    ocmfClientState: _builtins.bytes
    @_builtins.property
    def supportedEncryptionVersions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        publicKey: _builtins.bytes | None = ...,
        epochAuthPublicKey: _builtins.bytes | None = ...,
        epochAuthPublicKeySig: _builtins.bytes | None = ...,
        epochStoragePublicKey: _builtins.bytes | None = ...,
        epochStoragePublicKeySig: _builtins.bytes | None = ...,
        supportedEncryptionVersions: _abc.Iterable[_builtins.int] | None = ...,
        encryptionVersionSignature: _builtins.bytes | None = ...,
        clientVersion: _builtins.int | None = ...,
        ocmfClientState: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clientVersion", b"clientVersion", "encryptionVersionSignature", b"encryptionVersionSignature", "epochAuthPublicKey", b"epochAuthPublicKey", "epochAuthPublicKeySig", b"epochAuthPublicKeySig", "epochStoragePublicKey", b"epochStoragePublicKey", "epochStoragePublicKeySig", b"epochStoragePublicKeySig", "ocmfClientState", b"ocmfClientState", "publicKey", b"publicKey"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clientVersion", b"clientVersion", "encryptionVersionSignature", b"encryptionVersionSignature", "epochAuthPublicKey", b"epochAuthPublicKey", "epochAuthPublicKeySig", b"epochAuthPublicKeySig", "epochStoragePublicKey", b"epochStoragePublicKey", "epochStoragePublicKeySig", b"epochStoragePublicKeySig", "ocmfClientState", b"ocmfClientState", "publicKey", b"publicKey", "supportedEncryptionVersions", b"supportedEncryptionVersions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceOutput: _TypeAlias = DeviceOutput  # noqa: Y015

@_typing.final
class EncryptedSecretValuesOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENCRYPTEDDEVICEPRIVATEKEY_FIELD_NUMBER: _builtins.int
    ENCRYPTEDOBLIVIOUSVALIDATIONTOKENBLOB_FIELD_NUMBER: _builtins.int
    ENCRYPTEDEPOCHSTORAGEPRIVATEKEY_FIELD_NUMBER: _builtins.int
    ENCRYPTEDOCMFCLIENTSTATE_FIELD_NUMBER: _builtins.int
    ENCRYPTEDORFCLIENTSTATEV2_FIELD_NUMBER: _builtins.int
    ENCRYPTEDMAILBOXROOTKEYBLOB_FIELD_NUMBER: _builtins.int
    ENCRYPTEDEPOCHANONID_FIELD_NUMBER: _builtins.int
    ENCRYPTEDEPOCHROOTKEY_FIELD_NUMBER: _builtins.int
    encryptedDevicePrivateKey: _builtins.bytes
    encryptedObliviousValidationTokenBlob: _builtins.bytes
    encryptedEpochStoragePrivateKey: _builtins.bytes
    encryptedOcmfClientState: _builtins.bytes
    encryptedOrfClientStateV2: _builtins.bytes
    encryptedMailboxRootKeyBlob: _builtins.bytes
    encryptedEpochAnonID: _builtins.bytes
    encryptedEpochRootKey: _builtins.bytes
    def __init__(
        self,
        *,
        encryptedDevicePrivateKey: _builtins.bytes | None = ...,
        encryptedObliviousValidationTokenBlob: _builtins.bytes | None = ...,
        encryptedEpochStoragePrivateKey: _builtins.bytes | None = ...,
        encryptedOcmfClientState: _builtins.bytes | None = ...,
        encryptedOrfClientStateV2: _builtins.bytes | None = ...,
        encryptedMailboxRootKeyBlob: _builtins.bytes | None = ...,
        encryptedEpochAnonID: _builtins.bytes | None = ...,
        encryptedEpochRootKey: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encryptedDevicePrivateKey", b"encryptedDevicePrivateKey", "encryptedEpochAnonID", b"encryptedEpochAnonID", "encryptedEpochRootKey", b"encryptedEpochRootKey", "encryptedEpochStoragePrivateKey", b"encryptedEpochStoragePrivateKey", "encryptedMailboxRootKeyBlob", b"encryptedMailboxRootKeyBlob", "encryptedObliviousValidationTokenBlob", b"encryptedObliviousValidationTokenBlob", "encryptedOcmfClientState", b"encryptedOcmfClientState", "encryptedOrfClientStateV2", b"encryptedOrfClientStateV2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encryptedDevicePrivateKey", b"encryptedDevicePrivateKey", "encryptedEpochAnonID", b"encryptedEpochAnonID", "encryptedEpochRootKey", b"encryptedEpochRootKey", "encryptedEpochStoragePrivateKey", b"encryptedEpochStoragePrivateKey", "encryptedMailboxRootKeyBlob", b"encryptedMailboxRootKeyBlob", "encryptedObliviousValidationTokenBlob", b"encryptedObliviousValidationTokenBlob", "encryptedOcmfClientState", b"encryptedOcmfClientState", "encryptedOrfClientStateV2", b"encryptedOrfClientStateV2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EncryptedSecretValuesOutput: _TypeAlias = EncryptedSecretValuesOutput  # noqa: Y015

@_typing.final
class VirtualDeviceOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VDID_FIELD_NUMBER: _builtins.int
    VDPUBLICKEY_FIELD_NUMBER: _builtins.int
    VDEPOCHSTORAGEPUBLICKEY_FIELD_NUMBER: _builtins.int
    VDEPOCHSTORAGEPUBLICKEYSIG_FIELD_NUMBER: _builtins.int
    OCMFROTATIONTOKEN_FIELD_NUMBER: _builtins.int
    DEVICEEPOCHHMAC_FIELD_NUMBER: _builtins.int
    ENCRYPTEDSECRETVALUES_FIELD_NUMBER: _builtins.int
    vdID: _builtins.bytes
    vdPublicKey: _builtins.bytes
    vdEpochStoragePublicKey: _builtins.bytes
    vdEpochStoragePublicKeySig: _builtins.bytes
    ocmfRotationToken: _builtins.bytes
    deviceEpochHmac: _builtins.bytes
    @_builtins.property
    def encryptedSecretValues(self) -> Global___EncryptedSecretValuesOutput: ...
    def __init__(
        self,
        *,
        vdID: _builtins.bytes | None = ...,
        vdPublicKey: _builtins.bytes | None = ...,
        vdEpochStoragePublicKey: _builtins.bytes | None = ...,
        vdEpochStoragePublicKeySig: _builtins.bytes | None = ...,
        ocmfRotationToken: _builtins.bytes | None = ...,
        deviceEpochHmac: _builtins.bytes | None = ...,
        encryptedSecretValues: Global___EncryptedSecretValuesOutput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deviceEpochHmac", b"deviceEpochHmac", "encryptedSecretValues", b"encryptedSecretValues", "ocmfRotationToken", b"ocmfRotationToken", "vdEpochStoragePublicKey", b"vdEpochStoragePublicKey", "vdEpochStoragePublicKeySig", b"vdEpochStoragePublicKeySig", "vdID", b"vdID", "vdPublicKey", b"vdPublicKey"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deviceEpochHmac", b"deviceEpochHmac", "encryptedSecretValues", b"encryptedSecretValues", "ocmfRotationToken", b"ocmfRotationToken", "vdEpochStoragePublicKey", b"vdEpochStoragePublicKey", "vdEpochStoragePublicKeySig", b"vdEpochStoragePublicKeySig", "vdID", b"vdID", "vdPublicKey", b"vdPublicKey"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VirtualDeviceOutput: _TypeAlias = VirtualDeviceOutput  # noqa: Y015

@_typing.final
class Epoch0Output(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EPOCHFBID_FIELD_NUMBER: _builtins.int
    EPOCHANONID_FIELD_NUMBER: _builtins.int
    EPOCHDATA_FIELD_NUMBER: _builtins.int
    WRAPPEDROOTKEYFORSELF_FIELD_NUMBER: _builtins.int
    EPOCHSIGNATURE_FIELD_NUMBER: _builtins.int
    EPOCHROOTKEYFINGERPRINT_FIELD_NUMBER: _builtins.int
    EPOCHROOTKEY_FIELD_NUMBER: _builtins.int
    epochFbid: _builtins.int
    epochAnonID: _builtins.bytes
    epochData: _builtins.bytes
    wrappedRootKeyForSelf: _builtins.bytes
    epochSignature: _builtins.bytes
    epochRootKeyFingerprint: _builtins.bytes
    epochRootKey: _builtins.bytes
    def __init__(
        self,
        *,
        epochFbid: _builtins.int | None = ...,
        epochAnonID: _builtins.bytes | None = ...,
        epochData: _builtins.bytes | None = ...,
        wrappedRootKeyForSelf: _builtins.bytes | None = ...,
        epochSignature: _builtins.bytes | None = ...,
        epochRootKeyFingerprint: _builtins.bytes | None = ...,
        epochRootKey: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["epochAnonID", b"epochAnonID", "epochData", b"epochData", "epochFbid", b"epochFbid", "epochRootKey", b"epochRootKey", "epochRootKeyFingerprint", b"epochRootKeyFingerprint", "epochSignature", b"epochSignature", "wrappedRootKeyForSelf", b"wrappedRootKeyForSelf"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["epochAnonID", b"epochAnonID", "epochData", b"epochData", "epochFbid", b"epochFbid", "epochRootKey", b"epochRootKey", "epochRootKeyFingerprint", b"epochRootKeyFingerprint", "epochSignature", b"epochSignature", "wrappedRootKeyForSelf", b"wrappedRootKeyForSelf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Epoch0Output: _TypeAlias = Epoch0Output  # noqa: Y015

@_typing.final
class CreateBackupOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_FIELD_NUMBER: _builtins.int
    VIRTUALDEVICE_FIELD_NUMBER: _builtins.int
    EPOCH0_FIELD_NUMBER: _builtins.int
    MAILBOXROOTKEY_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    mailboxRootKey: _builtins.bytes
    error: _builtins.str
    @_builtins.property
    def device(self) -> Global___DeviceOutput: ...
    @_builtins.property
    def virtualDevice(self) -> Global___VirtualDeviceOutput: ...
    @_builtins.property
    def epoch0(self) -> Global___Epoch0Output: ...
    def __init__(
        self,
        *,
        device: Global___DeviceOutput | None = ...,
        virtualDevice: Global___VirtualDeviceOutput | None = ...,
        epoch0: Global___Epoch0Output | None = ...,
        mailboxRootKey: _builtins.bytes | None = ...,
        error: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "epoch0", b"epoch0", "error", b"error", "mailboxRootKey", b"mailboxRootKey", "virtualDevice", b"virtualDevice"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "epoch0", b"epoch0", "error", b"error", "mailboxRootKey", b"mailboxRootKey", "virtualDevice", b"virtualDevice"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateBackupOutput: _TypeAlias = CreateBackupOutput  # noqa: Y015

@_typing.final
class EncryptMessageOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENCRYPTEDPROTOBUF_FIELD_NUMBER: _builtins.int
    ORFTHREADID_FIELD_NUMBER: _builtins.int
    VALUESECRETREF_FIELD_NUMBER: _builtins.int
    OFFLINETHREADINGID_FIELD_NUMBER: _builtins.int
    TIMESTAMPMS_FIELD_NUMBER: _builtins.int
    MESSAGEKEY_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    encryptedProtobuf: _builtins.bytes
    orfThreadID: _builtins.bytes
    valueSecretRef: _builtins.str
    offlineThreadingID: _builtins.int
    timestampMS: _builtins.int
    messageKey: _builtins.bytes
    error: _builtins.str
    def __init__(
        self,
        *,
        encryptedProtobuf: _builtins.bytes | None = ...,
        orfThreadID: _builtins.bytes | None = ...,
        valueSecretRef: _builtins.str | None = ...,
        offlineThreadingID: _builtins.int | None = ...,
        timestampMS: _builtins.int | None = ...,
        messageKey: _builtins.bytes | None = ...,
        error: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encryptedProtobuf", b"encryptedProtobuf", "error", b"error", "messageKey", b"messageKey", "offlineThreadingID", b"offlineThreadingID", "orfThreadID", b"orfThreadID", "timestampMS", b"timestampMS", "valueSecretRef", b"valueSecretRef"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encryptedProtobuf", b"encryptedProtobuf", "error", b"error", "messageKey", b"messageKey", "offlineThreadingID", b"offlineThreadingID", "orfThreadID", b"orfThreadID", "timestampMS", b"timestampMS", "valueSecretRef", b"valueSecretRef"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EncryptMessageOutput: _TypeAlias = EncryptMessageOutput  # noqa: Y015

@_typing.final
class DecryptMessageOutput(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLAINTEXTPAYLOAD_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    plaintextPayload: _builtins.bytes
    error: _builtins.str
    def __init__(
        self,
        *,
        plaintextPayload: _builtins.bytes | None = ...,
        error: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "plaintextPayload", b"plaintextPayload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "plaintextPayload", b"plaintextPayload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DecryptMessageOutput: _TypeAlias = DecryptMessageOutput  # noqa: Y015

@_typing.final
class LabyrinthWaCommand(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREATEBACKUPINPUT_FIELD_NUMBER: _builtins.int
    ENCRYPTMESSAGEINPUT_FIELD_NUMBER: _builtins.int
    DECRYPTMESSAGEINPUT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def createBackupInput(self) -> Global___CreateBackupInput: ...
    @_builtins.property
    def encryptMessageInput(self) -> Global___EncryptMessageInput: ...
    @_builtins.property
    def decryptMessageInput(self) -> Global___DecryptMessageInput: ...
    def __init__(
        self,
        *,
        createBackupInput: Global___CreateBackupInput | None = ...,
        encryptMessageInput: Global___EncryptMessageInput | None = ...,
        decryptMessageInput: Global___DecryptMessageInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commandInput", b"commandInput", "createBackupInput", b"createBackupInput", "decryptMessageInput", b"decryptMessageInput", "encryptMessageInput", b"encryptMessageInput"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commandInput", b"commandInput", "createBackupInput", b"createBackupInput", "decryptMessageInput", b"decryptMessageInput", "encryptMessageInput", b"encryptMessageInput"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_commandInput: _TypeAlias = _typing.Literal["createBackupInput", "encryptMessageInput", "decryptMessageInput"]  # noqa: Y015
    _WhichOneofArgType_commandInput: _TypeAlias = _typing.Literal["commandInput", b"commandInput"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_commandInput) -> _WhichOneofReturnType_commandInput | None: ...

Global___LabyrinthWaCommand: _TypeAlias = LabyrinthWaCommand  # noqa: Y015
