"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AdminMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICEADMINMESSAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def deviceAdminMessage(self) -> Global___DeviceAdminMessage: ...
    def __init__(
        self,
        *,
        deviceAdminMessage: Global___DeviceAdminMessage | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adminMessageSubtype", b"adminMessageSubtype", "deviceAdminMessage", b"deviceAdminMessage"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adminMessageSubtype", b"adminMessageSubtype", "deviceAdminMessage", b"deviceAdminMessage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_adminMessageSubtype: _TypeAlias = _typing.Literal["deviceAdminMessage"]  # noqa: Y015
    _WhichOneofArgType_adminMessageSubtype: _TypeAlias = _typing.Literal["adminMessageSubtype", b"adminMessageSubtype"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_adminMessageSubtype) -> _WhichOneofReturnType_adminMessageSubtype | None: ...

Global___AdminMessage: _TypeAlias = AdminMessage  # noqa: Y015

@_typing.final
class DeviceAdminMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DeviceAdminMessage._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEVICE_ADMIN_MESSAGE_TYPE_NONE: DeviceAdminMessage._Type.ValueType  # 0
        DEVICE_ADMIN_MESSAGE_TYPE_LOCAL_USER_CHANGED_IDENTITY_KEY_NAMED_DEVICE: DeviceAdminMessage._Type.ValueType  # 1
        DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_KEY_CHANGE: DeviceAdminMessage._Type.ValueType  # 2
        DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_NEW_LOGIN: DeviceAdminMessage._Type.ValueType  # 3

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    DEVICE_ADMIN_MESSAGE_TYPE_NONE: DeviceAdminMessage.Type.ValueType  # 0
    DEVICE_ADMIN_MESSAGE_TYPE_LOCAL_USER_CHANGED_IDENTITY_KEY_NAMED_DEVICE: DeviceAdminMessage.Type.ValueType  # 1
    DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_KEY_CHANGE: DeviceAdminMessage.Type.ValueType  # 2
    DEVICE_ADMIN_MESSAGE_TYPE_SECURITY_ALERT_PARTICIPANT_NEW_LOGIN: DeviceAdminMessage.Type.ValueType  # 3

    DEVICEADMINMESSAGETYPE_FIELD_NUMBER: _builtins.int
    DEVICENAME_FIELD_NUMBER: _builtins.int
    deviceAdminMessageType: Global___DeviceAdminMessage.Type.ValueType
    deviceName: _builtins.str
    def __init__(
        self,
        *,
        deviceAdminMessageType: Global___DeviceAdminMessage.Type.ValueType | None = ...,
        deviceName: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["deviceAdminMessageType", b"deviceAdminMessageType", "deviceName", b"deviceName"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["deviceAdminMessageType", b"deviceAdminMessageType", "deviceName", b"deviceName"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeviceAdminMessage: _TypeAlias = DeviceAdminMessage  # noqa: Y015
