"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from waCommonParameterised import WACommonParameterised_pb2 as _WACommonParameterised_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ConsumerApplication(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Payload(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONTENT_FIELD_NUMBER: _builtins.int
        APPLICATIONDATA_FIELD_NUMBER: _builtins.int
        SIGNAL_FIELD_NUMBER: _builtins.int
        SUBPROTOCOL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def content(self) -> Global___ConsumerApplication.Content: ...
        @_builtins.property
        def applicationData(self) -> Global___ConsumerApplication.ApplicationData: ...
        @_builtins.property
        def signal(self) -> Global___ConsumerApplication.Signal: ...
        @_builtins.property
        def subProtocol(self) -> Global___ConsumerApplication.SubProtocolPayload: ...
        def __init__(
            self,
            *,
            content: Global___ConsumerApplication.Content | None = ...,
            applicationData: Global___ConsumerApplication.ApplicationData | None = ...,
            signal: Global___ConsumerApplication.Signal | None = ...,
            subProtocol: Global___ConsumerApplication.SubProtocolPayload | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["applicationData", b"applicationData", "content", b"content", "payload", b"payload", "signal", b"signal", "subProtocol", b"subProtocol"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["applicationData", b"applicationData", "content", b"content", "payload", b"payload", "signal", b"signal", "subProtocol", b"subProtocol"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["content", "applicationData", "signal", "subProtocol"]  # noqa: Y015
        _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

    @_typing.final
    class SubProtocolPayload(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        FUTUREPROOF_FIELD_NUMBER: _builtins.int
        futureProof: _WACommonParameterised_pb2.FutureProofBehavior.ValueType
        def __init__(
            self,
            *,
            futureProof: _WACommonParameterised_pb2.FutureProofBehavior.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["futureProof", b"futureProof"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["futureProof", b"futureProof"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Metadata(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _SpecialTextSize:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _SpecialTextSizeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ConsumerApplication.Metadata._SpecialTextSize.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            SMALL: ConsumerApplication.Metadata._SpecialTextSize.ValueType  # 1
            MEDIUM: ConsumerApplication.Metadata._SpecialTextSize.ValueType  # 2
            LARGE: ConsumerApplication.Metadata._SpecialTextSize.ValueType  # 3

        class SpecialTextSize(_SpecialTextSize, metaclass=_SpecialTextSizeEnumTypeWrapper): ...
        SMALL: ConsumerApplication.Metadata.SpecialTextSize.ValueType  # 1
        MEDIUM: ConsumerApplication.Metadata.SpecialTextSize.ValueType  # 2
        LARGE: ConsumerApplication.Metadata.SpecialTextSize.ValueType  # 3

        SPECIALTEXTSIZE_FIELD_NUMBER: _builtins.int
        specialTextSize: Global___ConsumerApplication.Metadata.SpecialTextSize.ValueType
        def __init__(
            self,
            *,
            specialTextSize: Global___ConsumerApplication.Metadata.SpecialTextSize.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["specialTextSize", b"specialTextSize"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["specialTextSize", b"specialTextSize"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Signal(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @_typing.final
    class ApplicationData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        REVOKE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def revoke(self) -> Global___ConsumerApplication.RevokeMessage: ...
        def __init__(
            self,
            *,
            revoke: Global___ConsumerApplication.RevokeMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["applicationContent", b"applicationContent", "revoke", b"revoke"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["applicationContent", b"applicationContent", "revoke", b"revoke"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_applicationContent: _TypeAlias = _typing.Literal["revoke"]  # noqa: Y015
        _WhichOneofArgType_applicationContent: _TypeAlias = _typing.Literal["applicationContent", b"applicationContent"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_applicationContent) -> _WhichOneofReturnType_applicationContent | None: ...

    @_typing.final
    class Content(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        MESSAGETEXT_FIELD_NUMBER: _builtins.int
        IMAGEMESSAGE_FIELD_NUMBER: _builtins.int
        CONTACTMESSAGE_FIELD_NUMBER: _builtins.int
        LOCATIONMESSAGE_FIELD_NUMBER: _builtins.int
        EXTENDEDTEXTMESSAGE_FIELD_NUMBER: _builtins.int
        STATUSTEXTMESSAGE_FIELD_NUMBER: _builtins.int
        DOCUMENTMESSAGE_FIELD_NUMBER: _builtins.int
        AUDIOMESSAGE_FIELD_NUMBER: _builtins.int
        VIDEOMESSAGE_FIELD_NUMBER: _builtins.int
        CONTACTSARRAYMESSAGE_FIELD_NUMBER: _builtins.int
        LIVELOCATIONMESSAGE_FIELD_NUMBER: _builtins.int
        STICKERMESSAGE_FIELD_NUMBER: _builtins.int
        GROUPINVITEMESSAGE_FIELD_NUMBER: _builtins.int
        VIEWONCEMESSAGE_FIELD_NUMBER: _builtins.int
        REACTIONMESSAGE_FIELD_NUMBER: _builtins.int
        POLLCREATIONMESSAGE_FIELD_NUMBER: _builtins.int
        POLLUPDATEMESSAGE_FIELD_NUMBER: _builtins.int
        EDITMESSAGE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def messageText(self) -> _WACommonParameterised_pb2.MessageText: ...
        @_builtins.property
        def imageMessage(self) -> Global___ConsumerApplication.ImageMessage: ...
        @_builtins.property
        def contactMessage(self) -> Global___ConsumerApplication.ContactMessage: ...
        @_builtins.property
        def locationMessage(self) -> Global___ConsumerApplication.LocationMessage: ...
        @_builtins.property
        def extendedTextMessage(self) -> Global___ConsumerApplication.ExtendedTextMessage: ...
        @_builtins.property
        def statusTextMessage(self) -> Global___ConsumerApplication.StatusTextMesage: ...
        @_builtins.property
        def documentMessage(self) -> Global___ConsumerApplication.DocumentMessage: ...
        @_builtins.property
        def audioMessage(self) -> Global___ConsumerApplication.AudioMessage: ...
        @_builtins.property
        def videoMessage(self) -> Global___ConsumerApplication.VideoMessage: ...
        @_builtins.property
        def contactsArrayMessage(self) -> Global___ConsumerApplication.ContactsArrayMessage: ...
        @_builtins.property
        def liveLocationMessage(self) -> Global___ConsumerApplication.LiveLocationMessage: ...
        @_builtins.property
        def stickerMessage(self) -> Global___ConsumerApplication.StickerMessage: ...
        @_builtins.property
        def groupInviteMessage(self) -> Global___ConsumerApplication.GroupInviteMessage: ...
        @_builtins.property
        def viewOnceMessage(self) -> Global___ConsumerApplication.ViewOnceMessage: ...
        @_builtins.property
        def reactionMessage(self) -> Global___ConsumerApplication.ReactionMessage: ...
        @_builtins.property
        def pollCreationMessage(self) -> Global___ConsumerApplication.PollCreationMessage: ...
        @_builtins.property
        def pollUpdateMessage(self) -> Global___ConsumerApplication.PollUpdateMessage: ...
        @_builtins.property
        def editMessage(self) -> Global___ConsumerApplication.EditMessage: ...
        def __init__(
            self,
            *,
            messageText: _WACommonParameterised_pb2.MessageText | None = ...,
            imageMessage: Global___ConsumerApplication.ImageMessage | None = ...,
            contactMessage: Global___ConsumerApplication.ContactMessage | None = ...,
            locationMessage: Global___ConsumerApplication.LocationMessage | None = ...,
            extendedTextMessage: Global___ConsumerApplication.ExtendedTextMessage | None = ...,
            statusTextMessage: Global___ConsumerApplication.StatusTextMesage | None = ...,
            documentMessage: Global___ConsumerApplication.DocumentMessage | None = ...,
            audioMessage: Global___ConsumerApplication.AudioMessage | None = ...,
            videoMessage: Global___ConsumerApplication.VideoMessage | None = ...,
            contactsArrayMessage: Global___ConsumerApplication.ContactsArrayMessage | None = ...,
            liveLocationMessage: Global___ConsumerApplication.LiveLocationMessage | None = ...,
            stickerMessage: Global___ConsumerApplication.StickerMessage | None = ...,
            groupInviteMessage: Global___ConsumerApplication.GroupInviteMessage | None = ...,
            viewOnceMessage: Global___ConsumerApplication.ViewOnceMessage | None = ...,
            reactionMessage: Global___ConsumerApplication.ReactionMessage | None = ...,
            pollCreationMessage: Global___ConsumerApplication.PollCreationMessage | None = ...,
            pollUpdateMessage: Global___ConsumerApplication.PollUpdateMessage | None = ...,
            editMessage: Global___ConsumerApplication.EditMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["audioMessage", b"audioMessage", "contactMessage", b"contactMessage", "contactsArrayMessage", b"contactsArrayMessage", "content", b"content", "documentMessage", b"documentMessage", "editMessage", b"editMessage", "extendedTextMessage", b"extendedTextMessage", "groupInviteMessage", b"groupInviteMessage", "imageMessage", b"imageMessage", "liveLocationMessage", b"liveLocationMessage", "locationMessage", b"locationMessage", "messageText", b"messageText", "pollCreationMessage", b"pollCreationMessage", "pollUpdateMessage", b"pollUpdateMessage", "reactionMessage", b"reactionMessage", "statusTextMessage", b"statusTextMessage", "stickerMessage", b"stickerMessage", "videoMessage", b"videoMessage", "viewOnceMessage", b"viewOnceMessage"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["audioMessage", b"audioMessage", "contactMessage", b"contactMessage", "contactsArrayMessage", b"contactsArrayMessage", "content", b"content", "documentMessage", b"documentMessage", "editMessage", b"editMessage", "extendedTextMessage", b"extendedTextMessage", "groupInviteMessage", b"groupInviteMessage", "imageMessage", b"imageMessage", "liveLocationMessage", b"liveLocationMessage", "locationMessage", b"locationMessage", "messageText", b"messageText", "pollCreationMessage", b"pollCreationMessage", "pollUpdateMessage", b"pollUpdateMessage", "reactionMessage", b"reactionMessage", "statusTextMessage", b"statusTextMessage", "stickerMessage", b"stickerMessage", "videoMessage", b"videoMessage", "viewOnceMessage", b"viewOnceMessage"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["messageText", "imageMessage", "contactMessage", "locationMessage", "extendedTextMessage", "statusTextMessage", "documentMessage", "audioMessage", "videoMessage", "contactsArrayMessage", "liveLocationMessage", "stickerMessage", "groupInviteMessage", "viewOnceMessage", "reactionMessage", "pollCreationMessage", "pollUpdateMessage", "editMessage"]  # noqa: Y015
        _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

    @_typing.final
    class EditMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        MESSAGE_FIELD_NUMBER: _builtins.int
        TIMESTAMPMS_FIELD_NUMBER: _builtins.int
        timestampMS: _builtins.int
        @_builtins.property
        def key(self) -> _WACommonParameterised_pb2.MessageKey: ...
        @_builtins.property
        def message(self) -> _WACommonParameterised_pb2.MessageText: ...
        def __init__(
            self,
            *,
            key: _WACommonParameterised_pb2.MessageKey | None = ...,
            message: _WACommonParameterised_pb2.MessageText | None = ...,
            timestampMS: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "message", b"message", "timestampMS", b"timestampMS"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "message", b"message", "timestampMS", b"timestampMS"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PollAddOptionMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        POLLOPTION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def pollOption(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConsumerApplication.Option]: ...
        def __init__(
            self,
            *,
            pollOption: _abc.Iterable[Global___ConsumerApplication.Option] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["pollOption", b"pollOption"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PollVoteMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SELECTEDOPTIONS_FIELD_NUMBER: _builtins.int
        SENDERTIMESTAMPMS_FIELD_NUMBER: _builtins.int
        senderTimestampMS: _builtins.int
        @_builtins.property
        def selectedOptions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
        def __init__(
            self,
            *,
            selectedOptions: _abc.Iterable[_builtins.bytes] | None = ...,
            senderTimestampMS: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["senderTimestampMS", b"senderTimestampMS"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["selectedOptions", b"selectedOptions", "senderTimestampMS", b"senderTimestampMS"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PollEncValue(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ENCPAYLOAD_FIELD_NUMBER: _builtins.int
        ENCIV_FIELD_NUMBER: _builtins.int
        encPayload: _builtins.bytes
        encIV: _builtins.bytes
        def __init__(
            self,
            *,
            encPayload: _builtins.bytes | None = ...,
            encIV: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["encIV", b"encIV", "encPayload", b"encPayload"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["encIV", b"encIV", "encPayload", b"encPayload"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PollUpdateMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        POLLCREATIONMESSAGEKEY_FIELD_NUMBER: _builtins.int
        VOTE_FIELD_NUMBER: _builtins.int
        ADDOPTION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def pollCreationMessageKey(self) -> _WACommonParameterised_pb2.MessageKey: ...
        @_builtins.property
        def vote(self) -> Global___ConsumerApplication.PollEncValue: ...
        @_builtins.property
        def addOption(self) -> Global___ConsumerApplication.PollEncValue: ...
        def __init__(
            self,
            *,
            pollCreationMessageKey: _WACommonParameterised_pb2.MessageKey | None = ...,
            vote: Global___ConsumerApplication.PollEncValue | None = ...,
            addOption: Global___ConsumerApplication.PollEncValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["addOption", b"addOption", "pollCreationMessageKey", b"pollCreationMessageKey", "vote", b"vote"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addOption", b"addOption", "pollCreationMessageKey", b"pollCreationMessageKey", "vote", b"vote"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class PollCreationMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ENCKEY_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        OPTIONS_FIELD_NUMBER: _builtins.int
        SELECTABLEOPTIONSCOUNT_FIELD_NUMBER: _builtins.int
        encKey: _builtins.bytes
        name: _builtins.str
        selectableOptionsCount: _builtins.int
        @_builtins.property
        def options(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConsumerApplication.Option]: ...
        def __init__(
            self,
            *,
            encKey: _builtins.bytes | None = ...,
            name: _builtins.str | None = ...,
            options: _abc.Iterable[Global___ConsumerApplication.Option] | None = ...,
            selectableOptionsCount: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["encKey", b"encKey", "name", b"name", "selectableOptionsCount", b"selectableOptionsCount"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["encKey", b"encKey", "name", b"name", "options", b"options", "selectableOptionsCount", b"selectableOptionsCount"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Option(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        OPTIONNAME_FIELD_NUMBER: _builtins.int
        optionName: _builtins.str
        def __init__(
            self,
            *,
            optionName: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["optionName", b"optionName"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["optionName", b"optionName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ReactionMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        TEXT_FIELD_NUMBER: _builtins.int
        GROUPINGKEY_FIELD_NUMBER: _builtins.int
        SENDERTIMESTAMPMS_FIELD_NUMBER: _builtins.int
        REACTIONMETADATADATACLASSDATA_FIELD_NUMBER: _builtins.int
        STYLE_FIELD_NUMBER: _builtins.int
        text: _builtins.str
        groupingKey: _builtins.str
        senderTimestampMS: _builtins.int
        reactionMetadataDataclassData: _builtins.str
        style: _builtins.int
        @_builtins.property
        def key(self) -> _WACommonParameterised_pb2.MessageKey: ...
        def __init__(
            self,
            *,
            key: _WACommonParameterised_pb2.MessageKey | None = ...,
            text: _builtins.str | None = ...,
            groupingKey: _builtins.str | None = ...,
            senderTimestampMS: _builtins.int | None = ...,
            reactionMetadataDataclassData: _builtins.str | None = ...,
            style: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["groupingKey", b"groupingKey", "key", b"key", "reactionMetadataDataclassData", b"reactionMetadataDataclassData", "senderTimestampMS", b"senderTimestampMS", "style", b"style", "text", b"text"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["groupingKey", b"groupingKey", "key", b"key", "reactionMetadataDataclassData", b"reactionMetadataDataclassData", "senderTimestampMS", b"senderTimestampMS", "style", b"style", "text", b"text"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class RevokeMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def key(self) -> _WACommonParameterised_pb2.MessageKey: ...
        def __init__(
            self,
            *,
            key: _WACommonParameterised_pb2.MessageKey | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ViewOnceMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        IMAGEMESSAGE_FIELD_NUMBER: _builtins.int
        VIDEOMESSAGE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def imageMessage(self) -> Global___ConsumerApplication.ImageMessage: ...
        @_builtins.property
        def videoMessage(self) -> Global___ConsumerApplication.VideoMessage: ...
        def __init__(
            self,
            *,
            imageMessage: Global___ConsumerApplication.ImageMessage | None = ...,
            videoMessage: Global___ConsumerApplication.VideoMessage | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["imageMessage", b"imageMessage", "videoMessage", b"videoMessage", "viewOnceContent", b"viewOnceContent"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["imageMessage", b"imageMessage", "videoMessage", b"videoMessage", "viewOnceContent", b"viewOnceContent"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_viewOnceContent: _TypeAlias = _typing.Literal["imageMessage", "videoMessage"]  # noqa: Y015
        _WhichOneofArgType_viewOnceContent: _TypeAlias = _typing.Literal["viewOnceContent", b"viewOnceContent"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_viewOnceContent) -> _WhichOneofReturnType_viewOnceContent | None: ...

    @_typing.final
    class GroupInviteMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GROUPJID_FIELD_NUMBER: _builtins.int
        INVITECODE_FIELD_NUMBER: _builtins.int
        INVITEEXPIRATION_FIELD_NUMBER: _builtins.int
        GROUPNAME_FIELD_NUMBER: _builtins.int
        JPEGTHUMBNAIL_FIELD_NUMBER: _builtins.int
        CAPTION_FIELD_NUMBER: _builtins.int
        groupJID: _builtins.str
        inviteCode: _builtins.str
        inviteExpiration: _builtins.int
        groupName: _builtins.str
        JPEGThumbnail: _builtins.bytes
        @_builtins.property
        def caption(self) -> _WACommonParameterised_pb2.MessageText: ...
        def __init__(
            self,
            *,
            groupJID: _builtins.str | None = ...,
            inviteCode: _builtins.str | None = ...,
            inviteExpiration: _builtins.int | None = ...,
            groupName: _builtins.str | None = ...,
            JPEGThumbnail: _builtins.bytes | None = ...,
            caption: _WACommonParameterised_pb2.MessageText | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["JPEGThumbnail", b"JPEGThumbnail", "caption", b"caption", "groupJID", b"groupJID", "groupName", b"groupName", "inviteCode", b"inviteCode", "inviteExpiration", b"inviteExpiration"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["JPEGThumbnail", b"JPEGThumbnail", "caption", b"caption", "groupJID", b"groupJID", "groupName", b"groupName", "inviteCode", b"inviteCode", "inviteExpiration", b"inviteExpiration"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LiveLocationMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LOCATION_FIELD_NUMBER: _builtins.int
        ACCURACYINMETERS_FIELD_NUMBER: _builtins.int
        SPEEDINMPS_FIELD_NUMBER: _builtins.int
        DEGREESCLOCKWISEFROMMAGNETICNORTH_FIELD_NUMBER: _builtins.int
        CAPTION_FIELD_NUMBER: _builtins.int
        SEQUENCENUMBER_FIELD_NUMBER: _builtins.int
        TIMEOFFSET_FIELD_NUMBER: _builtins.int
        accuracyInMeters: _builtins.int
        speedInMps: _builtins.float
        degreesClockwiseFromMagneticNorth: _builtins.int
        sequenceNumber: _builtins.int
        timeOffset: _builtins.int
        @_builtins.property
        def location(self) -> Global___ConsumerApplication.Location: ...
        @_builtins.property
        def caption(self) -> _WACommonParameterised_pb2.MessageText: ...
        def __init__(
            self,
            *,
            location: Global___ConsumerApplication.Location | None = ...,
            accuracyInMeters: _builtins.int | None = ...,
            speedInMps: _builtins.float | None = ...,
            degreesClockwiseFromMagneticNorth: _builtins.int | None = ...,
            caption: _WACommonParameterised_pb2.MessageText | None = ...,
            sequenceNumber: _builtins.int | None = ...,
            timeOffset: _builtins.int | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["accuracyInMeters", b"accuracyInMeters", "caption", b"caption", "degreesClockwiseFromMagneticNorth", b"degreesClockwiseFromMagneticNorth", "location", b"location", "sequenceNumber", b"sequenceNumber", "speedInMps", b"speedInMps", "timeOffset", b"timeOffset"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["accuracyInMeters", b"accuracyInMeters", "caption", b"caption", "degreesClockwiseFromMagneticNorth", b"degreesClockwiseFromMagneticNorth", "location", b"location", "sequenceNumber", b"sequenceNumber", "speedInMps", b"speedInMps", "timeOffset", b"timeOffset"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ContactsArrayMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DISPLAYNAME_FIELD_NUMBER: _builtins.int
        CONTACTS_FIELD_NUMBER: _builtins.int
        displayName: _builtins.str
        @_builtins.property
        def contacts(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConsumerApplication.ContactMessage]: ...
        def __init__(
            self,
            *,
            displayName: _builtins.str | None = ...,
            contacts: _abc.Iterable[Global___ConsumerApplication.ContactMessage] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["displayName", b"displayName"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["contacts", b"contacts", "displayName", b"displayName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ContactMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        CONTACT_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def contact(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            contact: _WACommonParameterised_pb2.SubProtocol | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["contact", b"contact"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["contact", b"contact"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StatusTextMesage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _FontType:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _FontTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ConsumerApplication.StatusTextMesage._FontType.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            SANS_SERIF: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 0
            SERIF: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 1
            NORICAN_REGULAR: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 2
            BRYNDAN_WRITE: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 3
            BEBASNEUE_REGULAR: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 4
            OSWALD_HEAVY: ConsumerApplication.StatusTextMesage._FontType.ValueType  # 5

        class FontType(_FontType, metaclass=_FontTypeEnumTypeWrapper): ...
        SANS_SERIF: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 0
        SERIF: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 1
        NORICAN_REGULAR: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 2
        BRYNDAN_WRITE: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 3
        BEBASNEUE_REGULAR: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 4
        OSWALD_HEAVY: ConsumerApplication.StatusTextMesage.FontType.ValueType  # 5

        TEXT_FIELD_NUMBER: _builtins.int
        TEXTARGB_FIELD_NUMBER: _builtins.int
        BACKGROUNDARGB_FIELD_NUMBER: _builtins.int
        FONT_FIELD_NUMBER: _builtins.int
        textArgb: _builtins.int
        backgroundArgb: _builtins.int
        font: Global___ConsumerApplication.StatusTextMesage.FontType.ValueType
        @_builtins.property
        def text(self) -> Global___ConsumerApplication.ExtendedTextMessage: ...
        def __init__(
            self,
            *,
            text: Global___ConsumerApplication.ExtendedTextMessage | None = ...,
            textArgb: _builtins.int | None = ...,
            backgroundArgb: _builtins.int | None = ...,
            font: Global___ConsumerApplication.StatusTextMesage.FontType.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["backgroundArgb", b"backgroundArgb", "font", b"font", "text", b"text", "textArgb", b"textArgb"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["backgroundArgb", b"backgroundArgb", "font", b"font", "text", b"text", "textArgb", b"textArgb"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ExtendedTextMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        class _PreviewType:
            ValueType = _typing.NewType("ValueType", _builtins.int)
            V: _TypeAlias = ValueType  # noqa: Y015

        class _PreviewTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ConsumerApplication.ExtendedTextMessage._PreviewType.ValueType], _builtins.type):
            DESCRIPTOR: _descriptor.EnumDescriptor
            NONE: ConsumerApplication.ExtendedTextMessage._PreviewType.ValueType  # 0
            VIDEO: ConsumerApplication.ExtendedTextMessage._PreviewType.ValueType  # 1

        class PreviewType(_PreviewType, metaclass=_PreviewTypeEnumTypeWrapper): ...
        NONE: ConsumerApplication.ExtendedTextMessage.PreviewType.ValueType  # 0
        VIDEO: ConsumerApplication.ExtendedTextMessage.PreviewType.ValueType  # 1

        TEXT_FIELD_NUMBER: _builtins.int
        MATCHEDTEXT_FIELD_NUMBER: _builtins.int
        CANONICALURL_FIELD_NUMBER: _builtins.int
        DESCRIPTION_FIELD_NUMBER: _builtins.int
        TITLE_FIELD_NUMBER: _builtins.int
        THUMBNAIL_FIELD_NUMBER: _builtins.int
        PREVIEWTYPE_FIELD_NUMBER: _builtins.int
        matchedText: _builtins.str
        canonicalURL: _builtins.str
        description: _builtins.str
        title: _builtins.str
        previewType: Global___ConsumerApplication.ExtendedTextMessage.PreviewType.ValueType
        @_builtins.property
        def text(self) -> _WACommonParameterised_pb2.MessageText: ...
        @_builtins.property
        def thumbnail(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            text: _WACommonParameterised_pb2.MessageText | None = ...,
            matchedText: _builtins.str | None = ...,
            canonicalURL: _builtins.str | None = ...,
            description: _builtins.str | None = ...,
            title: _builtins.str | None = ...,
            thumbnail: _WACommonParameterised_pb2.SubProtocol | None = ...,
            previewType: Global___ConsumerApplication.ExtendedTextMessage.PreviewType.ValueType | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["canonicalURL", b"canonicalURL", "description", b"description", "matchedText", b"matchedText", "previewType", b"previewType", "text", b"text", "thumbnail", b"thumbnail", "title", b"title"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["canonicalURL", b"canonicalURL", "description", b"description", "matchedText", b"matchedText", "previewType", b"previewType", "text", b"text", "thumbnail", b"thumbnail", "title", b"title"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class LocationMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LOCATION_FIELD_NUMBER: _builtins.int
        ADDRESS_FIELD_NUMBER: _builtins.int
        address: _builtins.str
        @_builtins.property
        def location(self) -> Global___ConsumerApplication.Location: ...
        def __init__(
            self,
            *,
            location: Global___ConsumerApplication.Location | None = ...,
            address: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "location", b"location"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "location", b"location"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class StickerMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STICKER_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def sticker(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            sticker: _WACommonParameterised_pb2.SubProtocol | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["sticker", b"sticker"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["sticker", b"sticker"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DocumentMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DOCUMENT_FIELD_NUMBER: _builtins.int
        FILENAME_FIELD_NUMBER: _builtins.int
        fileName: _builtins.str
        @_builtins.property
        def document(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            document: _WACommonParameterised_pb2.SubProtocol | None = ...,
            fileName: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["document", b"document", "fileName", b"fileName"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["document", b"document", "fileName", b"fileName"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class VideoMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VIDEO_FIELD_NUMBER: _builtins.int
        CAPTION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def video(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        @_builtins.property
        def caption(self) -> _WACommonParameterised_pb2.MessageText: ...
        def __init__(
            self,
            *,
            video: _WACommonParameterised_pb2.SubProtocol | None = ...,
            caption: _WACommonParameterised_pb2.MessageText | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["caption", b"caption", "video", b"video"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["caption", b"caption", "video", b"video"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AudioMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        AUDIO_FIELD_NUMBER: _builtins.int
        PTT_FIELD_NUMBER: _builtins.int
        PTT: _builtins.bool
        @_builtins.property
        def audio(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            audio: _WACommonParameterised_pb2.SubProtocol | None = ...,
            PTT: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["PTT", b"PTT", "audio", b"audio"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["PTT", b"PTT", "audio", b"audio"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class ImageMessage(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        IMAGE_FIELD_NUMBER: _builtins.int
        CAPTION_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def image(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        @_builtins.property
        def caption(self) -> _WACommonParameterised_pb2.MessageText: ...
        def __init__(
            self,
            *,
            image: _WACommonParameterised_pb2.SubProtocol | None = ...,
            caption: _WACommonParameterised_pb2.MessageText | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["caption", b"caption", "image", b"image"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["caption", b"caption", "image", b"image"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class InteractiveAnnotation(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        LOCATION_FIELD_NUMBER: _builtins.int
        POLYGONVERTICES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def location(self) -> Global___ConsumerApplication.Location: ...
        @_builtins.property
        def polygonVertices(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConsumerApplication.Point]: ...
        def __init__(
            self,
            *,
            location: Global___ConsumerApplication.Location | None = ...,
            polygonVertices: _abc.Iterable[Global___ConsumerApplication.Point] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "location", b"location"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "location", b"location", "polygonVertices", b"polygonVertices"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        _WhichOneofReturnType_action: _TypeAlias = _typing.Literal["location"]  # noqa: Y015
        _WhichOneofArgType_action: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
        def WhichOneof(self, oneof_group: _WhichOneofArgType_action) -> _WhichOneofReturnType_action | None: ...

    @_typing.final
    class Point(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        X_FIELD_NUMBER: _builtins.int
        Y_FIELD_NUMBER: _builtins.int
        x: _builtins.float
        y: _builtins.float
        def __init__(
            self,
            *,
            x: _builtins.float | None = ...,
            y: _builtins.float | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Location(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DEGREESLATITUDE_FIELD_NUMBER: _builtins.int
        DEGREESLONGITUDE_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        degreesLatitude: _builtins.float
        degreesLongitude: _builtins.float
        name: _builtins.str
        def __init__(
            self,
            *,
            degreesLatitude: _builtins.float | None = ...,
            degreesLongitude: _builtins.float | None = ...,
            name: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["degreesLatitude", b"degreesLatitude", "degreesLongitude", b"degreesLongitude", "name", b"name"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["degreesLatitude", b"degreesLatitude", "degreesLongitude", b"degreesLongitude", "name", b"name"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class MediaPayload(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PROTOCOL_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def protocol(self) -> _WACommonParameterised_pb2.SubProtocol: ...
        def __init__(
            self,
            *,
            protocol: _WACommonParameterised_pb2.SubProtocol | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["protocol", b"protocol"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["protocol", b"protocol"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    PAYLOAD_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def payload(self) -> Global___ConsumerApplication.Payload: ...
    @_builtins.property
    def metadata(self) -> Global___ConsumerApplication.Metadata: ...
    def __init__(
        self,
        *,
        payload: Global___ConsumerApplication.Payload | None = ...,
        metadata: Global___ConsumerApplication.Metadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConsumerApplication: _TypeAlias = ConsumerApplication  # noqa: Y015
