// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: Neonize.proto

package neonize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User       *string `protobuf:"bytes,1,req,name=User" json:"User,omitempty"`
	RawAgent   *uint32 `protobuf:"varint,2,req,name=RawAgent" json:"RawAgent,omitempty"`
	Device     *uint32 `protobuf:"varint,3,req,name=Device" json:"Device,omitempty"`
	Integrator *uint32 `protobuf:"varint,4,req,name=Integrator" json:"Integrator,omitempty"`
	Server     *string `protobuf:"bytes,5,req,name=Server" json:"Server,omitempty"`
}

func (x *JID) Reset() {
	*x = JID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Neonize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JID) ProtoMessage() {}

func (x *JID) ProtoReflect() protoreflect.Message {
	mi := &file_Neonize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JID.ProtoReflect.Descriptor instead.
func (*JID) Descriptor() ([]byte, []int) {
	return file_Neonize_proto_rawDescGZIP(), []int{0}
}

func (x *JID) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *JID) GetRawAgent() uint32 {
	if x != nil && x.RawAgent != nil {
		return *x.RawAgent
	}
	return 0
}

func (x *JID) GetDevice() uint32 {
	if x != nil && x.Device != nil {
		return *x.Device
	}
	return 0
}

func (x *JID) GetIntegrator() uint32 {
	if x != nil && x.Integrator != nil {
		return *x.Integrator
	}
	return 0
}

func (x *JID) GetServer() string {
	if x != nil && x.Server != nil {
		return *x.Server
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url           *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	DirectPath    *string `protobuf:"bytes,2,req,name=DirectPath" json:"DirectPath,omitempty"`
	Handle        *string `protobuf:"bytes,3,req,name=Handle" json:"Handle,omitempty"`
	MediaKey      []byte  `protobuf:"bytes,4,req,name=MediaKey" json:"MediaKey,omitempty"`
	FileEncSHA256 []byte  `protobuf:"bytes,5,req,name=FileEncSHA256" json:"FileEncSHA256,omitempty"`
	FileSHA256    []byte  `protobuf:"bytes,6,req,name=FileSHA256" json:"FileSHA256,omitempty"`
	FileLength    *uint32 `protobuf:"varint,7,req,name=FileLength" json:"FileLength,omitempty"`
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Neonize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Neonize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_Neonize_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *UploadResponse) GetDirectPath() string {
	if x != nil && x.DirectPath != nil {
		return *x.DirectPath
	}
	return ""
}

func (x *UploadResponse) GetHandle() string {
	if x != nil && x.Handle != nil {
		return *x.Handle
	}
	return ""
}

func (x *UploadResponse) GetMediaKey() []byte {
	if x != nil {
		return x.MediaKey
	}
	return nil
}

func (x *UploadResponse) GetFileEncSHA256() []byte {
	if x != nil {
		return x.FileEncSHA256
	}
	return nil
}

func (x *UploadResponse) GetFileSHA256() []byte {
	if x != nil {
		return x.FileSHA256
	}
	return nil
}

func (x *UploadResponse) GetFileLength() uint32 {
	if x != nil && x.FileLength != nil {
		return *x.FileLength
	}
	return 0
}

type MessageSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat               *JID    `protobuf:"bytes,1,req,name=Chat" json:"Chat,omitempty"`
	Sender             *JID    `protobuf:"bytes,2,req,name=Sender" json:"Sender,omitempty"`
	IsFromMe           *bool   `protobuf:"varint,3,req,name=IsFromMe" json:"IsFromMe,omitempty"`
	IsGroup            *bool   `protobuf:"varint,4,req,name=IsGroup" json:"IsGroup,omitempty"`
	BroadcastListOwner *JID    `protobuf:"bytes,5,req,name=BroadcastListOwner" json:"BroadcastListOwner,omitempty"`
	ID                 *string `protobuf:"bytes,6,req,name=ID" json:"ID,omitempty"`
}

func (x *MessageSource) Reset() {
	*x = MessageSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Neonize_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSource) ProtoMessage() {}

func (x *MessageSource) ProtoReflect() protoreflect.Message {
	mi := &file_Neonize_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSource.ProtoReflect.Descriptor instead.
func (*MessageSource) Descriptor() ([]byte, []int) {
	return file_Neonize_proto_rawDescGZIP(), []int{2}
}

func (x *MessageSource) GetChat() *JID {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *MessageSource) GetSender() *JID {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *MessageSource) GetIsFromMe() bool {
	if x != nil && x.IsFromMe != nil {
		return *x.IsFromMe
	}
	return false
}

func (x *MessageSource) GetIsGroup() bool {
	if x != nil && x.IsGroup != nil {
		return *x.IsGroup
	}
	return false
}

func (x *MessageSource) GetBroadcastListOwner() *JID {
	if x != nil {
		return x.BroadcastListOwner
	}
	return nil
}

func (x *MessageSource) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

type DeviceSentMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DestinationJID *string `protobuf:"bytes,1,req,name=DestinationJID" json:"DestinationJID,omitempty"`
	Phash          *string `protobuf:"bytes,2,req,name=Phash" json:"Phash,omitempty"`
}

func (x *DeviceSentMeta) Reset() {
	*x = DeviceSentMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Neonize_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceSentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSentMeta) ProtoMessage() {}

func (x *DeviceSentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_Neonize_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSentMeta.ProtoReflect.Descriptor instead.
func (*DeviceSentMeta) Descriptor() ([]byte, []int) {
	return file_Neonize_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceSentMeta) GetDestinationJID() string {
	if x != nil && x.DestinationJID != nil {
		return *x.DestinationJID
	}
	return ""
}

func (x *DeviceSentMeta) GetPhash() string {
	if x != nil && x.Phash != nil {
		return *x.Phash
	}
	return ""
}

type MessageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageSource *MessageSource `protobuf:"bytes,1,req,name=MessageSource" json:"MessageSource,omitempty"`
	ID            *string        `protobuf:"bytes,2,req,name=ID" json:"ID,omitempty"`
	ServerID      *string        `protobuf:"bytes,3,req,name=ServerID" json:"ServerID,omitempty"`
	Type          *string        `protobuf:"bytes,4,req,name=Type" json:"Type,omitempty"`
	PushName      *string        `protobuf:"bytes,5,req,name=PushName" json:"PushName,omitempty"`
	Timestamp     *uint64        `protobuf:"varint,6,req,name=Timestamp" json:"Timestamp,omitempty"`
	Category      *string        `protobuf:"bytes,7,req,name=Category" json:"Category,omitempty"`
	Multicast     *bool          `protobuf:"varint,8,req,name=Multicast" json:"Multicast,omitempty"`
	MediaType     *string        `protobuf:"bytes,9,req,name=MediaType" json:"MediaType,omitempty"`
	EditAttribute *string        `protobuf:"bytes,10,req,name=EditAttribute" json:"EditAttribute,omitempty"`
}

func (x *MessageInfo) Reset() {
	*x = MessageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Neonize_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageInfo) ProtoMessage() {}

func (x *MessageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Neonize_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageInfo.ProtoReflect.Descriptor instead.
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return file_Neonize_proto_rawDescGZIP(), []int{4}
}

func (x *MessageInfo) GetMessageSource() *MessageSource {
	if x != nil {
		return x.MessageSource
	}
	return nil
}

func (x *MessageInfo) GetID() string {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return ""
}

func (x *MessageInfo) GetServerID() string {
	if x != nil && x.ServerID != nil {
		return *x.ServerID
	}
	return ""
}

func (x *MessageInfo) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *MessageInfo) GetPushName() string {
	if x != nil && x.PushName != nil {
		return *x.PushName
	}
	return ""
}

func (x *MessageInfo) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *MessageInfo) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *MessageInfo) GetMulticast() bool {
	if x != nil && x.Multicast != nil {
		return *x.Multicast
	}
	return false
}

func (x *MessageInfo) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *MessageInfo) GetEditAttribute() string {
	if x != nil && x.EditAttribute != nil {
		return *x.EditAttribute
	}
	return ""
}

var File_Neonize_proto protoreflect.FileDescriptor

var file_Neonize_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4e, 0x65, 0x6f, 0x6e, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x03, 0x4a, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x61, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x52, 0x61, 0x77, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xdc,
	0x01, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x65, 0x45,
	0x6e, 0x63, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x0d,
	0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x12, 0x1e, 0x0a,
	0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18, 0x06, 0x20, 0x02, 0x28,
	0x0c, 0x52, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x12, 0x1e, 0x0a,
	0x0a, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0xd5, 0x01,
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x1e, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x49, 0x44, 0x52, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x22, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x49, 0x44, 0x52, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x49, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x04, 0x20, 0x02, 0x28, 0x08,
	0x52, 0x07, 0x49, 0x73, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x3a, 0x0a, 0x12, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18,
	0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x49,
	0x44, 0x52, 0x12, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x06, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4e, 0x0a, 0x0e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x49, 0x44, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x0e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x50, 0x68, 0x61, 0x73, 0x68, 0x22, 0xc1, 0x02, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x08, 0x50, 0x75, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x63, 0x61, 0x73, 0x74, 0x18, 0x08, 0x20, 0x02, 0x28, 0x08, 0x52, 0x09, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x63, 0x61, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x09, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0d, 0x45, 0x64, 0x69, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6e,
	0x65, 0x6f, 0x6e, 0x69, 0x7a, 0x65,
}

var (
	file_Neonize_proto_rawDescOnce sync.Once
	file_Neonize_proto_rawDescData = file_Neonize_proto_rawDesc
)

func file_Neonize_proto_rawDescGZIP() []byte {
	file_Neonize_proto_rawDescOnce.Do(func() {
		file_Neonize_proto_rawDescData = protoimpl.X.CompressGZIP(file_Neonize_proto_rawDescData)
	})
	return file_Neonize_proto_rawDescData
}

var file_Neonize_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Neonize_proto_goTypes = []interface{}{
	(*JID)(nil),            // 0: proto.JID
	(*UploadResponse)(nil), // 1: proto.UploadResponse
	(*MessageSource)(nil),  // 2: proto.MessageSource
	(*DeviceSentMeta)(nil), // 3: proto.DeviceSentMeta
	(*MessageInfo)(nil),    // 4: proto.MessageInfo
}
var file_Neonize_proto_depIdxs = []int32{
	0, // 0: proto.MessageSource.Chat:type_name -> proto.JID
	0, // 1: proto.MessageSource.Sender:type_name -> proto.JID
	0, // 2: proto.MessageSource.BroadcastListOwner:type_name -> proto.JID
	2, // 3: proto.MessageInfo.MessageSource:type_name -> proto.MessageSource
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Neonize_proto_init() }
func file_Neonize_proto_init() {
	if File_Neonize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Neonize_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Neonize_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Neonize_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Neonize_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceSentMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Neonize_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Neonize_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Neonize_proto_goTypes,
		DependencyIndexes: file_Neonize_proto_depIdxs,
		MessageInfos:      file_Neonize_proto_msgTypes,
	}.Build()
	File_Neonize_proto = out.File
	file_Neonize_proto_rawDesc = nil
	file_Neonize_proto_goTypes = nil
	file_Neonize_proto_depIdxs = nil
}
